"""Shared pytest fixtures for Zorah Super Agents tests.

This module provides common fixtures for all tests:

- async_client: AsyncClient for API testing
- mock_neo4j: Mocked Neo4j client
- mock_pinecone: Mocked Pinecone client
- sample_business: Sample business entity
- sample_review: Sample review entity
- clean_registry: Reset AgentRegistry between tests
- mock_knowledge_store: Mocked KnowledgeStore
- sample_business_data: Sample business data for agent tests
- sample_analysis_result: Sample analysis result
- sample_report_content: Sample report content
- mock_llm_response: Mock LLM response factory
"""

import pytest
from unittest.mock import AsyncMock, MagicMock, patch
import json

from src.orchestration.discovery import AgentRegistry


@pytest.fixture
def clean_registry():
    """Reset AgentRegistry singleton before and after test."""
    AgentRegistry.reset_registry()
    yield
    AgentRegistry.reset_registry()


@pytest.fixture
def mock_neo4j():
    """Mock Neo4j client for tests."""
    mock = MagicMock()
    mock.query.return_value = []
    mock.create_node.return_value = None
    return mock


@pytest.fixture
def mock_pinecone():
    """Mock Pinecone client for tests."""
    mock = MagicMock()
    mock.query.return_value = []
    mock.upsert.return_value = None
    return mock


@pytest.fixture
def mock_embedding_service():
    """Mock embedding service for tests."""
    mock = AsyncMock()
    mock.embed.return_value = [0.1] * 1536  # OpenAI embedding dimension
    return mock


@pytest.fixture
def mock_knowledge_store(mock_neo4j, mock_pinecone, mock_embedding_service):
    """Mock KnowledgeStore with all dependencies mocked."""
    mock = MagicMock()
    mock.graph_db = mock_neo4j
    mock.vector_store = mock_pinecone
    mock.embedding_service = mock_embedding_service
    mock.namespace = "test"
    mock.query.return_value = []
    mock.store.return_value = None
    return mock


@pytest.fixture
def sample_business() -> dict:
    """Return a sample business for testing."""
    return {
        "id": "test_business_123",
        "name": "Test Restaurant",
        "address": "123 Test Street",
        "latitude": 37.7749,
        "longitude": -122.4194,
        "rating": 4.5,
        "review_count": 100,
    }


@pytest.fixture
def sample_review() -> dict:
    """Return a sample review for testing."""
    return {
        "id": "test_review_456",
        "business_id": "test_business_123",
        "text": "Great food and excellent service!",
        "rating": 5,
        "author": "Test User",
        "created_at": "2024-01-15T12:00:00Z",
    }


@pytest.fixture
def sample_business_data():
    """Sample business data for testing."""
    return {
        "businesses": [
            {
                "name": "Test Coffee Shop",
                "place_id": "ChIJtest123",
                "rating": 4.5,
                "rating_count": 127,
                "address": "123 Main St, Austin, TX",
                "primary_type": "coffee_shop",
            },
            {
                "name": "Competitor Cafe",
                "place_id": "ChIJtest456",
                "rating": 4.2,
                "rating_count": 89,
                "address": "456 Oak Ave, Austin, TX",
                "primary_type": "cafe",
            },
        ],
        "count": 2,
        "query": "coffee shops in Austin",
        "collected_at": "2026-01-19T12:00:00Z",
    }


@pytest.fixture
def sample_analysis_result():
    """Sample analysis result for testing."""
    return {
        "summary": "Market analysis of coffee shops in Austin",
        "insights": [
            "Average rating is 4.35 across 2 businesses",
            "Total reviews: 216",
            "Test Coffee Shop has competitive advantage with higher rating",
        ],
        "recommendations": [
            "Focus on review volume to compete with Test Coffee Shop",
            "Consider location near 123 Main St for foot traffic",
        ],
    }


@pytest.fixture
def sample_report_content():
    """Sample report content for testing."""
    return """# Competitive Intelligence Report

## Executive Summary
Analysis of coffee shops in Austin, TX market.

## Key Findings
- Average rating: 4.35/5
- Total businesses analyzed: 2
- Market leader: Test Coffee Shop

## Recommendations
1. Focus on review volume
2. Consider downtown Austin location

Generated by Zorah Research Agent
"""


@pytest.fixture
def mock_llm_response():
    """Mock LLM response for agent execution tests."""
    from langchain_core.messages import AIMessage

    def create_response(content):
        return AIMessage(content=content)

    return create_response
