"""LangGraph workflow for report generation and delivery.

This module defines the report workflow that:
1. Prepares analysis results into a report structure
2. Generates an executive summary using Claude
3. Creates chart data for visualizations
4. Renders a professional HTML email report
5. Sends the report via SendGrid

The HTML report is mobile-responsive and professionally styled.
"""

from __future__ import annotations

import asyncio
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import structlog
from jinja2 import Template
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field

from src.config.settings import get_settings
from src.graphs.state import ReportState, ReportStatus, create_report_state

logger = structlog.get_logger(__name__)


# =============================================================================
# Pydantic Models for Report Data
# =============================================================================


class ExecutiveSummary(BaseModel):
    """Executive summary generated by Claude."""

    summary: str = Field(
        description="2-3 sentence executive summary of the analysis"
    )
    headline: str = Field(
        description="One compelling headline for the report"
    )
    key_metric: str = Field(
        description="The most important metric to highlight"
    )


class ChartData(BaseModel):
    """Data prepared for charts."""

    sentiment_breakdown: dict[str, float] = Field(
        description="Percentage breakdown of sentiments"
    )
    theme_scores: list[dict[str, Any]] = Field(
        description="Themes with their scores for bar chart"
    )
    rating_comparison: list[dict[str, Any]] = Field(
        description="Rating comparison with competitors"
    )


# =============================================================================
# Prompt Templates
# =============================================================================


EXECUTIVE_SUMMARY_PROMPT = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a senior business consultant writing executive summaries for business owners. This could be any type of business — adapt your language to whatever industry the data describes.
Your summaries should be:
- Concise (2-3 sentences maximum)
- Focused on actionable insights
- Professional but accessible
- Highlighting the most impactful finding

Write as if speaking directly to a busy business owner who needs the key takeaway immediately.""",
    ),
    (
        "human",
        """Write an executive summary for {business_name}'s performance report.

Key Data:
- Overall Sentiment Score: {sentiment_score}/1.0
- Sentiment Trend: {sentiment_trend}
- Reviews Analyzed: {review_count}
- Market Position: {market_position}

Top Strengths: {strengths}
Areas for Improvement: {weaknesses}

Top Insight: {top_insight}
Top Recommendation: {top_recommendation}

Generate:
1. A compelling headline (5-8 words)
2. An executive summary (2-3 sentences)
3. The single most important metric to highlight""",
    ),
])


# =============================================================================
# HTML Email Template
# =============================================================================


HTML_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ business_name }} - Performance Report</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;line-height:1.6;color:#333;background-color:#f5f5f5;">
    <div style="max-width:680px;margin:0 auto;background-color:#ffffff;">

        <!-- Header -->
        <div style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);color:white;padding:40px 30px;text-align:center;">
            <h1 style="margin:0;font-size:28px;font-weight:700;letter-spacing:-0.5px;">{{ business_name }}</h1>
            <div style="font-size:14px;opacity:0.85;margin-top:6px;">Customer Intelligence Report</div>
            <div style="margin-top:15px;padding:8px 16px;background:rgba(255,255,255,0.1);border-radius:20px;display:inline-block;font-size:13px;">{{ report_period }}</div>
        </div>

        <!-- Executive Summary -->
        <div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:30px;">
            <div style="font-size:22px;font-weight:700;margin-bottom:15px;line-height:1.3;">{{ headline }}</div>
            <div style="font-size:15px;line-height:1.7;opacity:0.95;">{{ executive_summary }}</div>
            <div style="margin-top:20px;padding:15px 20px;background:rgba(255,255,255,0.15);border-radius:10px;display:inline-block;">
                <div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;opacity:0.8;">Key Metric</div>
                <div style="font-size:28px;font-weight:700;">{{ key_metric }}</div>
            </div>
        </div>

        <!-- Metrics Overview -->
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #667eea;display:inline-block;">Overview</h2>
            <!--[if mso]><table role="presentation" width="100%"><tr><td width="25%" valign="top"><![endif]-->
            <table role="presentation" style="width:100%;border-collapse:collapse;">
                <tr>
                    <td style="width:25%;padding:15px;text-align:center;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;border-radius:12px;">
                        <div style="font-size:32px;font-weight:700;line-height:1;">{{ rating }}</div>
                        <div style="font-size:12px;margin-top:8px;opacity:0.85;">Avg Rating</div>
                    </td>
                    <td style="width:4%;"></td>
                    <td style="width:21%;padding:15px;text-align:center;background:{% if sentiment_score >= 0.6 %}#e8f5e9;color:#2e7d32{% elif sentiment_score >= 0.3 %}#fff3e0;color:#ef6c00{% else %}#f5f5f5;color:#616161{% endif %};border-radius:12px;">
                        <div style="font-size:32px;font-weight:700;line-height:1;">{{ (sentiment_score * 100)|round|int }}%</div>
                        <div style="font-size:12px;margin-top:8px;opacity:0.85;">Positive</div>
                    </td>
                    <td style="width:4%;"></td>
                    <td style="width:21%;padding:15px;text-align:center;background:{% if trend == 'improving' %}#e8f5e9;color:#2e7d32{% elif trend == 'declining' %}#fff3e0;color:#ef6c00{% else %}#f5f5f5;color:#616161{% endif %};border-radius:12px;">
                        <div style="font-size:32px;font-weight:700;line-height:1;">{% if trend == 'improving' %}&#8593;{% elif trend == 'declining' %}&#8595;{% else %}&#8594;{% endif %}</div>
                        <div style="font-size:12px;margin-top:8px;opacity:0.85;">{{ trend|title }}</div>
                    </td>
                    <td style="width:4%;"></td>
                    <td style="width:21%;padding:15px;text-align:center;background:#f5f5f5;color:#616161;border-radius:12px;">
                        <div style="font-size:32px;font-weight:700;line-height:1;">{{ review_count }}</div>
                        <div style="font-size:12px;margin-top:8px;opacity:0.85;">Reviews</div>
                    </td>
                </tr>
            </table>

            {% if review_count < 5 %}
            <div style="margin-top:15px;padding:12px 16px;background:#fff3e0;border-radius:8px;font-size:13px;color:#ef6c00;">
                Note: Analysis is based on only {{ review_count }} review{{ 's' if review_count != 1 else '' }}. Results may be less reliable with a small sample.
            </div>
            {% endif %}

            <!-- Sentiment Breakdown Bar -->
            <h3 style="font-size:14px;color:#666;margin:20px 0 10px 0;">Sentiment Breakdown</h3>
            <div style="height:12px;border-radius:6px;overflow:hidden;display:flex;margin:0 0 10px 0;">
                <div style="background:#4caf50;width:{{ positive_pct }}%;"></div>
                <div style="background:#9e9e9e;width:{{ neutral_pct }}%;"></div>
                <div style="background:#f44336;width:{{ negative_pct }}%;"></div>
            </div>
            <table role="presentation" style="width:100%;font-size:13px;color:#666;">
                <tr>
                    <td><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#4caf50;vertical-align:middle;"></span> Positive {{ positive_pct|round|int }}%</td>
                    <td style="text-align:center;"><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#9e9e9e;vertical-align:middle;"></span> Neutral {{ neutral_pct|round|int }}%</td>
                    <td style="text-align:right;"><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:#f44336;vertical-align:middle;"></span> Negative {{ negative_pct|round|int }}%</td>
                </tr>
            </table>
        </div>

        <!-- What Customers Love -->
        {% if strength_themes %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #4caf50;display:inline-block;">What Customers Love</h2>

            {% for theme in strength_themes %}
            <div style="padding:18px;background:#f8f9fa;border-radius:10px;border-left:4px solid #4caf50;margin-bottom:12px;">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
                    <span style="font-weight:700;color:#1a1a2e;font-size:15px;">{{ theme.name }}</span>
                    <span style="background:#e8f5e9;color:#2e7d32;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;">{{ theme.mention_count }} of {{ review_count }} reviews</span>
                </div>
                {% if theme.example_quotes %}
                {% for quote in theme.example_quotes[:2] %}
                <div style="font-size:13px;color:#555;font-style:italic;padding:8px 0 0 12px;border-left:2px solid #e0e0e0;margin-top:6px;">"{{ quote|truncate(200) }}"</div>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- What Needs Attention -->
        {% if weakness_themes %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #ff9800;display:inline-block;">What Needs Attention</h2>

            {% for theme in weakness_themes %}
            <div style="padding:18px;background:#f8f9fa;border-radius:10px;border-left:4px solid #ff9800;margin-bottom:12px;">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
                    <span style="font-weight:700;color:#1a1a2e;font-size:15px;">{{ theme.name }}</span>
                    <span style="background:#fff3e0;color:#ef6c00;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;">{{ theme.mention_count }} of {{ review_count }} reviews</span>
                </div>
                {% if theme.example_quotes %}
                {% for quote in theme.example_quotes[:2] %}
                <div style="font-size:13px;color:#555;font-style:italic;padding:8px 0 0 12px;border-left:2px solid #e0e0e0;margin-top:6px;">"{{ quote|truncate(200) }}"</div>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #ff9800;display:inline-block;">What Needs Attention</h2>
            <div style="padding:12px 16px;background:#f0fdf4;border-left:4px solid #22c55e;border-radius:4px;color:#166534;margin-top:8px;">
                ✓ No significant concerns found in recent reviews
            </div>
        </div>
        {% endif %}

        <!-- Competitive Position -->
        {% if competitor_comparisons or competitive_advantages or competitive_gaps %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #667eea;display:inline-block;">Competitive Position</h2>

            <!-- Market position badge -->
            <div style="background:#f8f9fa;border-radius:12px;padding:20px;margin-bottom:15px;">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;">
                    <div>
                        <strong style="color:#1a1a2e;">Market Standing</strong>
                        <div style="font-size:13px;color:#666;">vs. {{ competitor_count }} local competitors</div>
                    </div>
                    <span style="padding:6px 14px;border-radius:20px;font-size:12px;font-weight:600;text-transform:uppercase;{% if market_position == 'leader' %}background:#e8f5e9;color:#2e7d32;{% elif market_position == 'competitive' %}background:#e3f2fd;color:#1565c0;{% elif market_position == 'lagging' %}background:#ffebee;color:#c62828;{% else %}background:#f5f5f5;color:#616161;{% endif %}">{{ market_position|title }}</span>
                </div>

                {% if competitive_advantages %}
                <div style="margin-top:10px;">
                    <strong style="font-size:13px;color:#4caf50;">Your Advantages:</strong>
                    <ul style="margin:8px 0 0 0;padding:0;list-style:none;">
                        {% for adv in competitive_advantages[:3] %}
                        <li style="padding:6px 0 6px 20px;position:relative;font-size:14px;color:#444;"><span style="position:absolute;left:0;color:#4caf50;font-weight:bold;">&#10003;</span> {{ adv }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% if competitive_gaps %}
                <div style="margin-top:12px;">
                    <strong style="font-size:13px;color:#ff9800;">Gaps to Close:</strong>
                    <ul style="margin:8px 0 0 0;padding:0;list-style:none;">
                        {% for gap in competitive_gaps[:3] %}
                        <li style="padding:6px 0 6px 20px;position:relative;font-size:14px;color:#444;"><span style="position:absolute;left:0;color:#ff9800;">&#8594;</span> {{ gap }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>

            <!-- Named competitor cards -->
            {% if competitor_comparisons %}
            {% for comp in competitor_comparisons[:3] %}
            <div style="background:#f8f9fa;border-radius:10px;padding:16px;margin-bottom:10px;border-left:4px solid #667eea;">
                <div style="display:flex;justify-content:space-between;align-items:center;">
                    <span style="font-weight:700;color:#1a1a2e;">{{ comp.competitor_name }}</span>
                    {% if comp.competitor_rating %}
                    <span style="background:#e3f2fd;color:#1565c0;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;">{{ comp.competitor_rating }} stars</span>
                    {% endif %}
                </div>
                {% if comp.strengths_vs_competitor %}
                <div style="font-size:13px;color:#2e7d32;margin-top:8px;">You beat them: {{ comp.strengths_vs_competitor|join(', ') }}</div>
                {% endif %}
                {% if comp.weaknesses_vs_competitor %}
                <div style="font-size:13px;color:#ef6c00;margin-top:4px;">They beat you: {{ comp.weaknesses_vs_competitor|join(', ') }}</div>
                {% endif %}
                {% if comp.opportunity %}
                <div style="font-size:13px;color:#1565c0;margin-top:4px;font-style:italic;">Opportunity: {{ comp.opportunity }}</div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% endif %}

        <!-- Key Insights -->
        {% if insights %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #667eea;display:inline-block;">Key Insights</h2>

            {% for insight in insights[:5] %}
            <div style="padding:18px;background:#f8f9fa;border-radius:10px;margin-bottom:12px;position:relative;padding-left:55px;">
                <div style="position:absolute;left:15px;top:50%;transform:translateY(-50%);width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;color:white;text-align:center;line-height:28px;{% if insight.priority == 'high' %}background:linear-gradient(135deg,#f44336 0%,#e91e63 100%);{% elif insight.priority == 'low' %}background:linear-gradient(135deg,#4caf50 0%,#8bc34a 100%);{% else %}background:linear-gradient(135deg,#ff9800 0%,#ffc107 100%);{% endif %}">{{ loop.index }}</div>
                <div style="font-weight:600;color:#1a1a2e;margin-bottom:4px;">{{ insight.title }}</div>
                <div style="font-size:14px;color:#555;">{{ insight.description }}</div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- Recommendations -->
        {% if recommendations %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 20px 0;padding-bottom:10px;border-bottom:3px solid #667eea;display:inline-block;">Recommended Actions</h2>

            {% for rec in recommendations[:5] %}
            <div style="padding:18px;background:#f8f9fa;border-radius:10px;margin-bottom:12px;position:relative;padding-left:55px;">
                <div style="position:absolute;left:15px;top:50%;transform:translateY(-50%);width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;color:white;text-align:center;line-height:28px;{% if rec.priority == 'high' %}background:linear-gradient(135deg,#f44336 0%,#e91e63 100%);{% elif rec.priority == 'low' %}background:linear-gradient(135deg,#4caf50 0%,#8bc34a 100%);{% else %}background:linear-gradient(135deg,#ff9800 0%,#ffc107 100%);{% endif %}">{{ loop.index }}</div>
                <div style="font-weight:600;color:#1a1a2e;margin-bottom:4px;">{{ rec.title }}</div>
                <div style="font-size:14px;color:#555;">{{ rec.description }}</div>
            </div>
            {% endfor %}

            {% if quick_wins %}
            <div style="background:linear-gradient(135deg,#4caf50 0%,#8bc34a 100%);color:white;border-radius:12px;padding:25px;margin-top:20px;">
                <h3 style="font-size:16px;margin:0 0 15px 0;">Quick Wins - Do This Week</h3>
                <ul style="list-style:none;margin:0;padding:0;">
                    {% for win in quick_wins[:3] %}
                    <li style="padding:10px 0 10px 25px;position:relative;{% if not loop.last %}border-bottom:1px solid rgba(255,255,255,0.2);{% endif %}"><span style="position:absolute;left:0;">&#9889;</span> {{ win }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
        {% endif %}

        <!-- Suggested Responses -->
        {% if review_responses %}
        <div style="padding:30px;border-bottom:1px solid #eee;">
            <h2 style="font-size:18px;font-weight:700;color:#1a1a2e;margin:0 0 6px 0;padding-bottom:10px;border-bottom:3px solid #667eea;display:inline-block;">Suggested Responses</h2>
            <p style="font-size:13px;color:#888;margin:0 0 20px 0;">AI-drafted replies for your most important reviews — copy, tweak &amp; post.</p>

            {% for resp in review_responses %}
            <div style="background:#f8f9fa;border-radius:10px;padding:20px;margin-bottom:14px;">
                <div style="margin-bottom:10px;">
                    <span style="font-weight:600;color:#1a1a2e;">{{ resp.reviewer_name }}</span>
                    <span style="margin-left:8px;font-size:13px;color:#f59e0b;">{% for i in range(resp.rating|int) %}&#9733;{% endfor %}{% for i in range(5 - resp.rating|int) %}&#9734;{% endfor %}</span>
                    <span style="float:right;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:#888;background:#eee;padding:3px 8px;border-radius:4px;">{{ resp.strategy | replace('_', ' ') | title }}</span>
                </div>
                <div style="font-size:13px;color:#666;font-style:italic;margin-bottom:12px;">&#8220;{{ resp.review_text[:100] }}{% if resp.review_text|length > 100 %}&hellip;{% endif %}&#8221;</div>
                <div style="background:#eef2ff;border-left:4px solid #667eea;border-radius:0 8px 8px 0;padding:14px;">
                    <p style="margin:0;color:#333;font-size:14px;line-height:1.6;">{{ resp.response_text }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- Footer -->
        <div style="background:#1a1a2e;color:white;padding:30px;text-align:center;">
            <div style="font-size:20px;font-weight:700;margin-bottom:10px;">LocalPulse</div>
            <div style="font-size:13px;opacity:0.7;margin-bottom:15px;">AI-Powered Business Intelligence</div>
            <div style="font-size:12px;opacity:0.5;">Generated on {{ generated_at }} | Questions? Reply to this email</div>
        </div>
    </div>
</body>
</html>
"""


# =============================================================================
# Node Functions
# =============================================================================


def _get_llm() -> ChatAnthropic:
    """Get configured Claude Haiku instance."""
    settings = get_settings()
    api_key = settings.anthropic_api_key
    if api_key:
        api_key = api_key.get_secret_value()

    return ChatAnthropic(
        model="claude-3-haiku-20240307",
        api_key=api_key,
        temperature=0.5,
        max_tokens=1024,
    )


async def prepare_report_data(state: ReportState) -> dict:
    """Gather analysis results into report structure.

    Args:
        state: Current report state with analysis data.

    Returns:
        Partial state update with prepared report data.
    """
    logger.info("report_prepare_data", business_id=state.get("business_id"))

    analysis = state.get("analysis", {})

    # Extract data from analysis
    sentiment_results = analysis.get("sentiment_results", {})
    theme_results = analysis.get("theme_results", [])
    competitor_analysis = analysis.get("competitor_analysis", {})
    insights = analysis.get("insights", [])
    recommendations = analysis.get("recommendations", [])
    review_responses = analysis.get("review_responses", [])

    # Get theme data
    theme_data = theme_results[0] if theme_results else {}

    # Separate themes into strengths and weaknesses with full data
    all_themes = theme_data.get("themes", [])
    strength_themes = [t for t in all_themes if t.get("is_strength", True)]
    weakness_themes = [t for t in all_themes if not t.get("is_strength", True)]

    # Sort by mention count descending
    strength_themes.sort(key=lambda t: t.get("mention_count", 0), reverse=True)
    weakness_themes.sort(key=lambda t: t.get("mention_count", 0), reverse=True)

    # Prepare report data structure
    report_data = {
        "business_name": sentiment_results.get("business_name", "Your Business"),
        "business_rating": sentiment_results.get("business_rating", 0),
        "sentiment_score": sentiment_results.get("overall_score", 0),
        "sentiment_trend": sentiment_results.get("trend", "stable"),
        "review_count": sentiment_results.get("review_count", 0),
        "positive_count": sentiment_results.get("positive_count", 0),
        "negative_count": sentiment_results.get("negative_count", 0),
        "neutral_count": sentiment_results.get("neutral_count", 0),
        "strengths": theme_data.get("top_strengths", []),
        "weaknesses": theme_data.get("top_weaknesses", []),
        "themes": all_themes,
        "strength_themes": strength_themes[:5],
        "weakness_themes": weakness_themes[:5],
        "market_position": competitor_analysis.get("market_position", "competitive"),
        "competitor_count": len(competitor_analysis.get("competitors", [])),
        "competitive_advantages": competitor_analysis.get("competitive_advantages", []),
        "competitive_gaps": competitor_analysis.get("competitive_gaps", []),
        "competitor_comparisons": competitor_analysis.get("comparisons", []),
        "insights": insights,
        "recommendations": recommendations,
        "quick_wins": sentiment_results.get("quick_wins", []),
        "detailed_insights": sentiment_results.get("detailed_insights", []),
        "detailed_recommendations": sentiment_results.get("detailed_recommendations", []),
        "review_responses": review_responses,
    }

    # Preserve owner_email: check state channel first, then analysis dict as fallback
    owner_email = state.get("owner_email") or analysis.get("owner_email")

    logger.info(
        "report_data_prepared",
        business_name=report_data["business_name"],
        review_count=report_data["review_count"],
        has_email=bool(owner_email),
    )

    result = {
        "report_data": report_data,
        "status": ReportStatus.GENERATING.value,
    }
    if owner_email:
        result["owner_email"] = owner_email
    return result


async def generate_executive_summary(state: ReportState) -> dict:
    """Generate executive summary using Claude.

    Args:
        state: Current state with report data.

    Returns:
        Partial state update with executive summary.
    """
    report_data = state.get("report_data", {})
    business_name = report_data.get("business_name", "Unknown")

    logger.info("report_generate_summary", business_name=business_name)

    try:
        # Get key data points
        sentiment_score = report_data.get("sentiment_score", 0)
        sentiment_trend = report_data.get("sentiment_trend", "stable")
        review_count = report_data.get("review_count", 0)
        market_position = report_data.get("market_position", "competitive")
        strengths = report_data.get("strengths", [])
        weaknesses = report_data.get("weaknesses", [])
        insights = report_data.get("insights", [])
        recommendations = report_data.get("recommendations", [])

        llm = _get_llm()
        structured_llm = llm.with_structured_output(ExecutiveSummary)

        prompt = EXECUTIVE_SUMMARY_PROMPT.format(
            business_name=business_name,
            sentiment_score=round(sentiment_score, 2),
            sentiment_trend=sentiment_trend,
            review_count=review_count,
            market_position=market_position,
            strengths=", ".join(strengths[:3]) if strengths else "Not identified",
            weaknesses=", ".join(weaknesses[:3]) if weaknesses else "Not identified",
            top_insight=insights[0] if insights else "No insights available",
            top_recommendation=recommendations[0] if recommendations else "No recommendations available",
        )

        result: ExecutiveSummary = await structured_llm.ainvoke(prompt)

        logger.info("report_summary_generated")

        return {
            "report_data": {
                **report_data,
                "executive_summary": result.summary,
                "headline": result.headline,
                "key_metric": result.key_metric,
            }
        }

    except Exception as e:
        logger.error("report_summary_failed", error=str(e))
        # Fallback summary
        return {
            "report_data": {
                **report_data,
                "executive_summary": f"Analysis of {report_data.get('review_count', 0)} customer reviews reveals key insights for {business_name}.",
                "headline": f"{business_name} Performance Report",
                "key_metric": f"{round(report_data.get('sentiment_score', 0) * 100)}% Positive",
            },
            "errors": [f"Summary generation failed: {str(e)}"],
        }


async def create_charts_data(state: ReportState) -> dict:
    """Prepare data for visualizations.

    Args:
        state: Current state with report data.

    Returns:
        Partial state update with chart data.
    """
    report_data = state.get("report_data", {})

    logger.info("report_create_charts")

    # Calculate sentiment percentages
    positive = report_data.get("positive_count", 0)
    negative = report_data.get("negative_count", 0)
    neutral = report_data.get("neutral_count", 0)
    total = positive + negative + neutral or 1

    sentiment_breakdown = {
        "positive": (positive / total) * 100,
        "neutral": (neutral / total) * 100,
        "negative": (negative / total) * 100,
    }

    # Prepare theme scores
    themes = report_data.get("themes", [])
    theme_scores = [
        {
            "name": theme.get("name", "Unknown"),
            "score": theme.get("average_sentiment", 0),
            "count": theme.get("mention_count", 0),
            "is_strength": theme.get("is_strength", True),
        }
        for theme in themes[:6]
    ]

    # Rating comparison (client vs average competitor)
    business_rating = report_data.get("business_rating", 0)
    rating_comparison = [
        {"name": report_data.get("business_name", "You"), "rating": business_rating},
        {"name": "Market Average", "rating": 4.2},  # Placeholder
    ]

    chart_data = {
        "sentiment_breakdown": sentiment_breakdown,
        "theme_scores": theme_scores,
        "rating_comparison": rating_comparison,
    }

    logger.info(
        "report_charts_created",
        positive_pct=round(sentiment_breakdown["positive"], 1),
    )

    return {
        "report_data": {
            **report_data,
            "chart_data": chart_data,
            "positive_pct": sentiment_breakdown["positive"],
            "neutral_pct": sentiment_breakdown["neutral"],
            "negative_pct": sentiment_breakdown["negative"],
        }
    }


async def render_html_report(state: ReportState) -> dict:
    """Render the HTML email report.

    Args:
        state: Current state with all report data.

    Returns:
        Partial state update with HTML report.
    """
    report_data = state.get("report_data", {})
    business_name = report_data.get("business_name", "Unknown")

    logger.info("report_render_html", business_name=business_name)

    try:
        # Parse insights and recommendations for template
        insights = report_data.get("insights", [])
        detailed_insights = report_data.get("detailed_insights", [])
        recommendations = report_data.get("recommendations", [])
        detailed_recommendations = report_data.get("detailed_recommendations", [])

        # Convert string insights to dict format for template
        insights_for_template = []
        for i, insight in enumerate(insights[:5]):
            if detailed_insights and i < len(detailed_insights):
                detail = detailed_insights[i]
                insights_for_template.append({
                    "title": detail.get("title", f"Insight {i+1}"),
                    "description": detail.get("description", insight),
                    "priority": detail.get("impact", "medium"),
                })
            else:
                # Parse from string format "[PRIORITY] Title: Description"
                parts = insight.split(": ", 1)
                title = parts[0].replace("[HIGH]", "").replace("[MEDIUM]", "").replace("[LOW]", "").strip()
                description = parts[1] if len(parts) > 1 else insight
                priority = "high" if "[HIGH]" in insight else ("low" if "[LOW]" in insight else "medium")
                insights_for_template.append({
                    "title": title,
                    "description": description,
                    "priority": priority,
                })

        # Convert recommendations similarly
        recommendations_for_template = []
        for i, rec in enumerate(recommendations[:5]):
            if detailed_recommendations and i < len(detailed_recommendations):
                detail = detailed_recommendations[i]
                recommendations_for_template.append({
                    "title": detail.get("title", f"Recommendation {i+1}"),
                    "description": detail.get("description", rec),
                    "priority": detail.get("priority", "medium"),
                })
            else:
                parts = rec.split(": ", 1)
                title = parts[0].replace("[HIGH]", "").replace("[MEDIUM]", "").replace("[LOW]", "").strip()
                description = parts[1] if len(parts) > 1 else rec
                priority = "high" if "[HIGH]" in rec else ("low" if "[LOW]" in rec else "medium")
                recommendations_for_template.append({
                    "title": title,
                    "description": description,
                    "priority": priority,
                })

        # Strip [RX] review citation tags from recommendation text fields
        _rx_pattern = re.compile(r'\[R\d+(?:,\s*R\d+)*\]')
        for rec in recommendations_for_template:
            for key in rec:
                if isinstance(rec[key], str):
                    rec[key] = _rx_pattern.sub('', rec[key]).strip()
        quick_wins_raw = report_data.get("quick_wins", [])[:3]
        quick_wins_clean = [_rx_pattern.sub('', w).strip() for w in quick_wins_raw if isinstance(w, str)]

        # Prepare template variables
        template_vars = {
            "business_name": business_name,
            "report_period": datetime.now(timezone.utc).strftime("%B %Y"),
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            "headline": report_data.get("headline", f"{business_name} Performance Report"),
            "executive_summary": report_data.get("executive_summary", ""),
            "key_metric": report_data.get("key_metric", "N/A"),
            "rating": report_data.get("business_rating", 0),
            "sentiment_score": report_data.get("sentiment_score", 0),
            "trend": report_data.get("sentiment_trend", "stable"),
            "review_count": report_data.get("review_count", 0),
            "positive_pct": report_data.get("positive_pct", 0),
            "neutral_pct": report_data.get("neutral_pct", 0),
            "negative_pct": report_data.get("negative_pct", 0),
            "strength_themes": report_data.get("strength_themes", []),
            "weakness_themes": report_data.get("weakness_themes", []),
            "market_position": report_data.get("market_position", "competitive"),
            "competitor_count": report_data.get("competitor_count", 0),
            "competitive_advantages": report_data.get("competitive_advantages", [])[:3],
            "competitive_gaps": report_data.get("competitive_gaps", [])[:3],
            "competitor_comparisons": report_data.get("competitor_comparisons", []),
            "insights": insights_for_template,
            "recommendations": recommendations_for_template,
            "quick_wins": quick_wins_clean,
            "review_responses": report_data.get("review_responses", []),
        }

        # Render template
        template = Template(HTML_REPORT_TEMPLATE)
        html = template.render(**template_vars)

        logger.info("report_html_rendered", html_length=len(html))

        return {
            "report_html": html,
            "status": ReportStatus.SENDING.value,
        }

    except Exception as e:
        logger.error("report_render_failed", error=str(e))
        return {
            "errors": [f"HTML render failed: {str(e)}"],
            "status": ReportStatus.FAILED.value,
        }


async def send_email(state: ReportState) -> dict:
    """Send the report via SendGrid using EmailService.

    Args:
        state: Current state with HTML report.

    Returns:
        Partial state update with email status.
    """
    html = state.get("report_html", "")
    report_data = state.get("report_data", {})
    business_name = report_data.get("business_name", "Unknown")
    owner_email = state.get("owner_email") or state.get("report_state", {}).get("owner_email")

    logger.info("report_send_email", business_name=business_name, has_email=bool(owner_email))

    # If no recipient email provided, skip sending
    if not owner_email:
        logger.warning("report_email_skipped", reason="No recipient email provided")
        return {
            "email_sent": False,
            "status": ReportStatus.COMPLETED.value,
        }

    try:
        # Use the EmailService to send the report
        from src.delivery.email_service import get_email_service

        email_service = get_email_service()

        if not email_service.is_configured:
            logger.warning("report_email_skipped", reason="Resend API key not configured")
            return {
                "email_sent": False,
                "status": ReportStatus.COMPLETED.value,
                "errors": ["Email skipped: Resend API key not configured"],
            }

        # Determine report period
        report_period = datetime.now(timezone.utc).strftime("%B %Y")

        # Send the report email
        success = await email_service.send_report(
            to_email=owner_email,
            business_name=business_name,
            report_html=html,
            report_date=report_period,
        )

        if success:
            logger.info("report_email_sent", to=owner_email)
            return {
                "email_sent": True,
                "status": ReportStatus.COMPLETED.value,
            }
        else:
            logger.error("report_email_failed", to=owner_email)
            return {
                "email_sent": False,
                "errors": ["Email send failed - check logs for details"],
                "status": ReportStatus.COMPLETED.value,
            }

    except Exception as e:
        logger.error("report_email_error", error=str(e))
        return {
            "email_sent": False,
            "errors": [f"Email send failed: {str(e)}"],
            "status": ReportStatus.COMPLETED.value,
        }


# =============================================================================
# Graph Builder
# =============================================================================


def create_report_graph() -> StateGraph:
    """Create the report generation workflow graph.

    The graph executes the following flow:
    1. prepare_report_data - Gather analysis results
    2. generate_executive_summary - Claude writes summary
    3. create_charts_data - Prepare visualization data
    4. render_html_report - Create HTML email
    5. send_email - Send via SendGrid

    Returns:
        StateGraph for report workflow.
    """
    workflow = StateGraph(ReportState)

    # Add nodes
    workflow.add_node("prepare_report_data", prepare_report_data)
    workflow.add_node("generate_executive_summary", generate_executive_summary)
    workflow.add_node("create_charts_data", create_charts_data)
    workflow.add_node("render_html_report", render_html_report)
    workflow.add_node("send_email", send_email)

    # Set entry point
    workflow.set_entry_point("prepare_report_data")

    # Add sequential edges
    workflow.add_edge("prepare_report_data", "generate_executive_summary")
    workflow.add_edge("generate_executive_summary", "create_charts_data")
    workflow.add_edge("create_charts_data", "render_html_report")
    workflow.add_edge("render_html_report", "send_email")
    workflow.add_edge("send_email", END)

    return workflow


def compile_report_graph():
    """Create and compile the report graph.

    Returns:
        Compiled graph ready for invocation.
    """
    graph = create_report_graph()
    return graph.compile()


# =============================================================================
# Convenience Function
# =============================================================================


async def run_report(
    business_id: str,
    analysis: dict[str, Any],
) -> ReportState:
    """Run the report workflow.

    Args:
        business_id: Business ID.
        analysis: Analysis results dict.

    Returns:
        Final ReportState with generated report.
    """
    initial_state = create_report_state(
        business_id=business_id,
        analysis=analysis,
    )

    graph = compile_report_graph()
    final_state = await graph.ainvoke(initial_state)

    return final_state


# =============================================================================
# Test Function
# =============================================================================


def _safe_print(text: str) -> None:
    """Print text safely, handling Unicode issues on Windows."""
    safe_text = text.encode("ascii", errors="replace").decode("ascii")
    print(safe_text)


async def test_report_workflow():
    """Test the report workflow using analysis results.

    Generates the full report and saves HTML to file.
    """
    _safe_print("=" * 70)
    _safe_print("Report Generation Workflow Test")
    _safe_print("=" * 70)

    # Create sample analysis data (mimicking analysis workflow output)
    analysis_data = {
        "sentiment_results": {
            "business_name": "Circolo Popolare Manchester",
            "business_rating": 4.9,
            "overall_score": 0.84,
            "trend": "improving",
            "review_count": 5,
            "positive_count": 4,
            "negative_count": 0,
            "neutral_count": 1,
            "summary": "The sentiment analysis indicates overwhelmingly positive customer feedback.",
            "executive_summary": "Circolo Popolare Manchester excels in customer satisfaction with a strong 84% positive sentiment score.",
            "quick_wins": [
                "Reinforce service training to maintain exceptional standards",
                "Evaluate pricing strategy to ensure strong value perception",
            ],
            "detailed_insights": [
                {"title": "Exceptional Service", "description": "Customers consistently praise the attentive and friendly staff", "impact": "high"},
                {"title": "Food Quality Leader", "description": "Fresh ingredients and authentic Italian flavors drive positive reviews", "impact": "high"},
                {"title": "Ambiance Excellence", "description": "The restaurant atmosphere creates memorable dining experiences", "impact": "medium"},
                {"title": "Value Perception", "description": "Some customers note prices are premium but justified by quality", "impact": "medium"},
                {"title": "Growth Opportunity", "description": "Expanding menu options could attract new customer segments", "impact": "low"},
            ],
            "detailed_recommendations": [
                {"title": "Staff Recognition Program", "description": "Implement a program to reward exceptional service", "priority": "high"},
                {"title": "Seasonal Menu Items", "description": "Introduce rotating seasonal specials to maintain interest", "priority": "medium"},
                {"title": "Loyalty Program", "description": "Create a loyalty program to increase repeat visits", "priority": "medium"},
                {"title": "Social Media Engagement", "description": "Increase social media presence to attract younger demographics", "priority": "low"},
                {"title": "Private Events", "description": "Promote private dining options for corporate events", "priority": "low"},
            ],
        },
        "theme_results": [{
            "top_strengths": ["Food Quality", "Ambiance", "Service"],
            "top_weaknesses": ["Service Inconsistency", "Automatic Service Charge"],
            "themes": [
                {"name": "Food Quality", "average_sentiment": 0.9, "mention_count": 5, "is_strength": True},
                {"name": "Service", "average_sentiment": 0.85, "mention_count": 4, "is_strength": True},
                {"name": "Ambiance", "average_sentiment": 0.8, "mention_count": 3, "is_strength": True},
                {"name": "Value", "average_sentiment": 0.5, "mention_count": 2, "is_strength": False},
            ],
            "summary": "Customers highlight exceptional food quality, service, and ambiance.",
        }],
        "competitor_analysis": {
            "competitors": [{"name": f"Competitor {i}"} for i in range(1, 20)],
            "market_position": "leader",
            "competitive_advantages": [
                "Higher overall customer rating (4.9 vs market average)",
                "Consistent positive feedback on food and service quality",
                "Strong brand reputation in the local market",
            ],
            "competitive_gaps": [
                "Pricing perceived as premium by some customers",
            ],
            "summary": "Circolo Popolare Manchester leads the competitive set with exceptional ratings.",
        },
        "insights": [
            "[HIGH] Maintain Exceptional Service: Customer service is a key differentiator",
            "[HIGH] Strengthen Brand: Leverage positive reputation for marketing",
            "[MEDIUM] Menu Innovation: Introduce seasonal items to maintain interest",
            "[MEDIUM] Value Communication: Better communicate the value proposition",
            "[LOW] Expand Private Dining: Opportunity in corporate events market",
        ],
        "recommendations": [
            "[HIGH] Staff Training Program: Implement ongoing service excellence training",
            "[HIGH] Social Media Strategy: Increase online presence and engagement",
            "[MEDIUM] Loyalty Program: Create rewards for repeat customers",
            "[MEDIUM] Seasonal Menu: Rotate specials to drive repeat visits",
            "[LOW] Private Events: Develop corporate dining packages",
        ],
    }

    business_id = "Circolo Popolare Manchester"

    _safe_print(f"\nGenerating report for: {business_id}")
    _safe_print("-" * 70)

    # Create initial state
    initial_state = create_report_state(
        business_id=business_id,
        analysis=analysis_data,
    )

    _safe_print(f"\nInitial State:")
    _safe_print(f"  Business ID: {business_id}")
    _safe_print(f"  Status: {initial_state.get('status')}")

    # Compile the graph
    graph = compile_report_graph()

    # Run with streaming
    _safe_print("\n" + "=" * 70)
    _safe_print("Workflow Execution:")
    _safe_print("=" * 70)

    step_count = 0
    accumulated_state = dict(initial_state)

    async for event in graph.astream(initial_state):
        step_count += 1
        for node_name, node_state in event.items():
            # Merge updates
            for key, value in node_state.items():
                if key == "errors" and isinstance(value, list):
                    existing = accumulated_state.get(key, [])
                    accumulated_state[key] = existing + value
                else:
                    accumulated_state[key] = value

            _safe_print(f"\n[Step {step_count}] {node_name}")
            _safe_print("-" * 40)

            if node_name == "prepare_report_data":
                report_data = accumulated_state.get("report_data", {})
                _safe_print(f"  Business: {report_data.get('business_name')}")
                _safe_print(f"  Reviews: {report_data.get('review_count')}")
                _safe_print(f"  Sentiment: {report_data.get('sentiment_score')}")

            elif node_name == "generate_executive_summary":
                report_data = accumulated_state.get("report_data", {})
                _safe_print(f"  Headline: {report_data.get('headline', 'N/A')[:50]}...")
                _safe_print(f"  Key Metric: {report_data.get('key_metric', 'N/A')}")

            elif node_name == "create_charts_data":
                report_data = accumulated_state.get("report_data", {})
                _safe_print(f"  Positive: {report_data.get('positive_pct', 0):.1f}%")
                _safe_print(f"  Neutral: {report_data.get('neutral_pct', 0):.1f}%")
                _safe_print(f"  Negative: {report_data.get('negative_pct', 0):.1f}%")

            elif node_name == "render_html_report":
                html = accumulated_state.get("report_html", "")
                _safe_print(f"  HTML Length: {len(html)} characters")

            elif node_name == "send_email":
                _safe_print(f"  Email Sent: {accumulated_state.get('email_sent', False)}")
                _safe_print(f"  Final Status: {accumulated_state.get('status')}")

    # Save HTML to file
    html = accumulated_state.get("report_html", "")
    if html:
        output_path = Path("report_preview.html")
        output_path.write_text(html, encoding="utf-8")
        _safe_print(f"\n[OK] Report saved to: {output_path.absolute()}")

    # Print summary
    _safe_print("\n" + "=" * 70)
    _safe_print("Report Generation Summary:")
    _safe_print("=" * 70)

    _safe_print(f"\n  Status: {accumulated_state.get('status')}")
    _safe_print(f"  HTML Generated: {len(accumulated_state.get('report_html', ''))} chars")
    _safe_print(f"  Email Sent: {accumulated_state.get('email_sent', False)}")

    if accumulated_state.get("errors"):
        _safe_print(f"\n  Errors: {accumulated_state.get('errors')}")

    _safe_print("\n" + "=" * 70)
    _safe_print("Test completed! Open report_preview.html to view the report.")
    _safe_print("=" * 70)

    return accumulated_state


if __name__ == "__main__":
    asyncio.run(test_report_workflow())
