"""LangGraph workflow for report generation and delivery.

This module defines the report workflow that:
1. Prepares analysis results into a report structure
2. Generates an executive summary using Claude
3. Creates chart data for visualizations
4. Renders a professional HTML email report
5. Sends the report via SendGrid

The HTML report is mobile-responsive and professionally styled.
"""

from __future__ import annotations

import asyncio
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import structlog
from jinja2 import Template
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field

from src.config.settings import get_settings
from src.graphs.state import ReportState, ReportStatus, create_report_state

logger = structlog.get_logger(__name__)


# =============================================================================
# Pydantic Models for Report Data
# =============================================================================


class ExecutiveSummary(BaseModel):
    """Executive summary generated by Claude."""

    summary: str = Field(
        description="2-3 sentence executive summary of the analysis"
    )
    headline: str = Field(
        description="One compelling headline for the report"
    )
    key_metric: str = Field(
        description="The most important metric to highlight"
    )


class ChartData(BaseModel):
    """Data prepared for charts."""

    sentiment_breakdown: dict[str, float] = Field(
        description="Percentage breakdown of sentiments"
    )
    theme_scores: list[dict[str, Any]] = Field(
        description="Themes with their scores for bar chart"
    )
    rating_comparison: list[dict[str, Any]] = Field(
        description="Rating comparison with competitors"
    )


# =============================================================================
# Prompt Templates
# =============================================================================


EXECUTIVE_SUMMARY_PROMPT = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a senior hospitality consultant writing executive summaries for restaurant owners.
Your summaries should be:
- Concise (2-3 sentences maximum)
- Focused on actionable insights
- Professional but accessible
- Highlighting the most impactful finding

Write as if speaking directly to a busy restaurant owner who needs the key takeaway immediately.""",
    ),
    (
        "human",
        """Write an executive summary for {business_name}'s performance report.

Key Data:
- Overall Sentiment Score: {sentiment_score}/1.0
- Sentiment Trend: {sentiment_trend}
- Reviews Analyzed: {review_count}
- Market Position: {market_position}

Top Strengths: {strengths}
Areas for Improvement: {weaknesses}

Top Insight: {top_insight}
Top Recommendation: {top_recommendation}

Generate:
1. A compelling headline (5-8 words)
2. An executive summary (2-3 sentences)
3. The single most important metric to highlight""",
    ),
])


# =============================================================================
# HTML Email Template
# =============================================================================


HTML_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ business_name }} - Performance Report</title>
    <style>
        /* Reset and Base Styles */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }

        /* Container */
        .email-container {
            max-width: 680px;
            margin: 0 auto;
            background-color: #ffffff;
        }

        /* Header */
        .header {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }

        .header h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            letter-spacing: -0.5px;
        }

        .header .subtitle {
            font-size: 14px;
            opacity: 0.85;
            font-weight: 400;
        }

        .header .report-period {
            margin-top: 15px;
            padding: 8px 16px;
            background: rgba(255,255,255,0.1);
            border-radius: 20px;
            display: inline-block;
            font-size: 13px;
        }

        /* Executive Summary */
        .executive-summary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
        }

        .executive-summary .headline {
            font-size: 22px;
            font-weight: 700;
            margin-bottom: 15px;
            line-height: 1.3;
        }

        .executive-summary .summary-text {
            font-size: 15px;
            line-height: 1.7;
            opacity: 0.95;
        }

        .key-metric {
            margin-top: 20px;
            padding: 15px 20px;
            background: rgba(255,255,255,0.15);
            border-radius: 10px;
            display: inline-block;
        }

        .key-metric .label {
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 1px;
            opacity: 0.8;
        }

        .key-metric .value {
            font-size: 28px;
            font-weight: 700;
        }

        /* Section Styles */
        .section {
            padding: 30px;
            border-bottom: 1px solid #eee;
        }

        .section:last-child {
            border-bottom: none;
        }

        .section-title {
            font-size: 18px;
            font-weight: 700;
            color: #1a1a2e;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 3px solid #667eea;
            display: inline-block;
        }

        /* Score Cards */
        .score-cards {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
            margin-bottom: 20px;
        }

        .score-card {
            flex: 1;
            min-width: 140px;
            padding: 20px;
            border-radius: 12px;
            text-align: center;
        }

        .score-card.primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }

        .score-card.success {
            background: #e8f5e9;
            color: #2e7d32;
        }

        .score-card.warning {
            background: #fff3e0;
            color: #ef6c00;
        }

        .score-card.neutral {
            background: #f5f5f5;
            color: #616161;
        }

        .score-card .score-value {
            font-size: 32px;
            font-weight: 700;
            line-height: 1;
        }

        .score-card .score-label {
            font-size: 12px;
            margin-top: 8px;
            opacity: 0.85;
        }

        /* Sentiment Bar */
        .sentiment-bar {
            height: 12px;
            border-radius: 6px;
            overflow: hidden;
            display: flex;
            margin: 15px 0;
        }

        .sentiment-bar .positive {
            background: #4caf50;
        }

        .sentiment-bar .neutral {
            background: #9e9e9e;
        }

        .sentiment-bar .negative {
            background: #f44336;
        }

        .sentiment-legend {
            display: flex;
            justify-content: space-between;
            font-size: 13px;
            color: #666;
        }

        .sentiment-legend span {
            display: flex;
            align-items: center;
            gap: 6px;
        }

        .sentiment-legend .dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
        }

        .sentiment-legend .dot.positive { background: #4caf50; }
        .sentiment-legend .dot.neutral { background: #9e9e9e; }
        .sentiment-legend .dot.negative { background: #f44336; }

        /* Theme List */
        .theme-list {
            display: flex;
            flex-direction: column;
            gap: 12px;
        }

        .theme-item {
            display: flex;
            align-items: center;
            gap: 15px;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 10px;
        }

        .theme-item.strength {
            border-left: 4px solid #4caf50;
        }

        .theme-item.weakness {
            border-left: 4px solid #ff9800;
        }

        .theme-icon {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 18px;
        }

        .theme-icon.strength {
            background: #e8f5e9;
        }

        .theme-icon.weakness {
            background: #fff3e0;
        }

        .theme-content {
            flex: 1;
        }

        .theme-name {
            font-weight: 600;
            color: #1a1a2e;
        }

        .theme-detail {
            font-size: 13px;
            color: #666;
            margin-top: 3px;
        }

        /* Competitor Section */
        .competitor-card {
            background: #f8f9fa;
            border-radius: 12px;
            padding: 20px;
            margin-bottom: 15px;
        }

        .competitor-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }

        .market-position {
            padding: 6px 14px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
        }

        .market-position.leader {
            background: #e8f5e9;
            color: #2e7d32;
        }

        .market-position.competitive {
            background: #e3f2fd;
            color: #1565c0;
        }

        .market-position.lagging {
            background: #ffebee;
            color: #c62828;
        }

        .advantages-list, .gaps-list {
            margin-top: 10px;
        }

        .advantages-list li, .gaps-list li {
            padding: 8px 0;
            padding-left: 25px;
            position: relative;
            font-size: 14px;
            color: #444;
        }

        .advantages-list li::before {
            content: "✓";
            position: absolute;
            left: 0;
            color: #4caf50;
            font-weight: bold;
        }

        .gaps-list li::before {
            content: "→";
            position: absolute;
            left: 0;
            color: #ff9800;
        }

        /* Insights & Recommendations */
        .insight-list, .recommendation-list {
            display: flex;
            flex-direction: column;
            gap: 12px;
        }

        .insight-item, .recommendation-item {
            padding: 18px;
            background: #f8f9fa;
            border-radius: 10px;
            position: relative;
            padding-left: 60px;
        }

        .priority-badge {
            position: absolute;
            left: 15px;
            top: 50%;
            transform: translateY(-50%);
            width: 32px;
            height: 32px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            font-weight: 700;
            color: white;
        }

        .priority-badge.high {
            background: linear-gradient(135deg, #f44336 0%, #e91e63 100%);
        }

        .priority-badge.medium {
            background: linear-gradient(135deg, #ff9800 0%, #ffc107 100%);
        }

        .priority-badge.low {
            background: linear-gradient(135deg, #4caf50 0%, #8bc34a 100%);
        }

        .insight-title, .recommendation-title {
            font-weight: 600;
            color: #1a1a2e;
            margin-bottom: 5px;
        }

        .insight-text, .recommendation-text {
            font-size: 14px;
            color: #555;
        }

        /* Quick Wins */
        .quick-wins {
            background: linear-gradient(135deg, #4caf50 0%, #8bc34a 100%);
            color: white;
            border-radius: 12px;
            padding: 25px;
            margin-top: 20px;
        }

        .quick-wins h3 {
            font-size: 16px;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .quick-wins ul {
            list-style: none;
        }

        .quick-wins li {
            padding: 10px 0;
            padding-left: 30px;
            position: relative;
            border-bottom: 1px solid rgba(255,255,255,0.2);
        }

        .quick-wins li:last-child {
            border-bottom: none;
        }

        .quick-wins li::before {
            content: "⚡";
            position: absolute;
            left: 0;
        }

        /* Footer */
        .footer {
            background: #1a1a2e;
            color: white;
            padding: 30px;
            text-align: center;
        }

        .footer-logo {
            font-size: 20px;
            font-weight: 700;
            margin-bottom: 10px;
        }

        .footer-text {
            font-size: 13px;
            opacity: 0.7;
            margin-bottom: 15px;
        }

        .footer-links {
            font-size: 12px;
            opacity: 0.5;
        }

        /* Mobile Responsive */
        @media (max-width: 600px) {
            .header {
                padding: 30px 20px;
            }

            .header h1 {
                font-size: 24px;
            }

            .section {
                padding: 25px 20px;
            }

            .score-cards {
                flex-direction: column;
            }

            .score-card {
                min-width: 100%;
            }

            .executive-summary .headline {
                font-size: 20px;
            }

            .theme-item {
                flex-direction: column;
                text-align: center;
            }

            .insight-item, .recommendation-item {
                padding-left: 18px;
                padding-top: 50px;
            }

            .priority-badge {
                left: 50%;
                top: 15px;
                transform: translateX(-50%);
            }
        }
    </style>
</head>
<body>
    <div class="email-container">
        <!-- Header -->
        <div class="header">
            <h1>{{ business_name }}</h1>
            <div class="subtitle">Customer Intelligence Report</div>
            <div class="report-period">{{ report_period }}</div>
        </div>

        <!-- Executive Summary -->
        <div class="executive-summary">
            <div class="headline">{{ headline }}</div>
            <div class="summary-text">{{ executive_summary }}</div>
            <div class="key-metric">
                <div class="label">Key Metric</div>
                <div class="value">{{ key_metric }}</div>
            </div>
        </div>

        <!-- Overall Performance -->
        <div class="section">
            <h2 class="section-title">Overall Performance</h2>
            <div class="score-cards">
                <div class="score-card primary">
                    <div class="score-value">{{ rating }}</div>
                    <div class="score-label">Average Rating</div>
                </div>
                <div class="score-card {% if sentiment_score >= 0.6 %}success{% elif sentiment_score >= 0.3 %}warning{% else %}neutral{% endif %}">
                    <div class="score-value">{{ (sentiment_score * 100)|round|int }}%</div>
                    <div class="score-label">Positive Sentiment</div>
                </div>
                <div class="score-card {% if trend == 'improving' %}success{% elif trend == 'declining' %}warning{% else %}neutral{% endif %}">
                    <div class="score-value">{% if trend == 'improving' %}↑{% elif trend == 'declining' %}↓{% else %}→{% endif %}</div>
                    <div class="score-label">{{ trend|title }} Trend</div>
                </div>
                <div class="score-card neutral">
                    <div class="score-value">{{ review_count }}</div>
                    <div class="score-label">Reviews Analyzed</div>
                </div>
            </div>

            <!-- Sentiment Breakdown -->
            <h3 style="font-size: 14px; color: #666; margin-bottom: 10px;">Sentiment Breakdown</h3>
            <div class="sentiment-bar">
                <div class="positive" style="width: {{ positive_pct }}%"></div>
                <div class="neutral" style="width: {{ neutral_pct }}%"></div>
                <div class="negative" style="width: {{ negative_pct }}%"></div>
            </div>
            <div class="sentiment-legend">
                <span><span class="dot positive"></span> Positive {{ positive_pct|round|int }}%</span>
                <span><span class="dot neutral"></span> Neutral {{ neutral_pct|round|int }}%</span>
                <span><span class="dot negative"></span> Negative {{ negative_pct|round|int }}%</span>
            </div>
        </div>

        <!-- Themes Analysis -->
        <div class="section">
            <h2 class="section-title">What Customers Are Saying</h2>

            {% if strengths %}
            <h3 style="font-size: 14px; color: #4caf50; margin-bottom: 15px;">✓ Your Strengths</h3>
            <div class="theme-list" style="margin-bottom: 25px;">
                {% for strength in strengths %}
                <div class="theme-item strength">
                    <div class="theme-icon strength">👍</div>
                    <div class="theme-content">
                        <div class="theme-name">{{ strength }}</div>
                        <div class="theme-detail">Customers consistently praise this</div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {% if weaknesses %}
            <h3 style="font-size: 14px; color: #ff9800; margin-bottom: 15px;">→ Areas for Improvement</h3>
            <div class="theme-list">
                {% for weakness in weaknesses %}
                <div class="theme-item weakness">
                    <div class="theme-icon weakness">📌</div>
                    <div class="theme-content">
                        <div class="theme-name">{{ weakness }}</div>
                        <div class="theme-detail">Opportunity to improve customer satisfaction</div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>

        <!-- Competitive Position -->
        <div class="section">
            <h2 class="section-title">Competitive Position</h2>
            <div class="competitor-card">
                <div class="competitor-header">
                    <div>
                        <strong style="color: #1a1a2e;">Market Standing</strong>
                        <div style="font-size: 13px; color: #666;">vs. {{ competitor_count }} local competitors</div>
                    </div>
                    <div class="market-position {{ market_position }}">{{ market_position|title }}</div>
                </div>

                {% if competitive_advantages %}
                <div class="advantages-list">
                    <strong style="font-size: 13px; color: #4caf50;">Your Advantages:</strong>
                    <ul style="margin-top: 8px;">
                        {% for advantage in competitive_advantages[:3] %}
                        <li>{{ advantage }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% if competitive_gaps %}
                <div class="gaps-list" style="margin-top: 15px;">
                    <strong style="font-size: 13px; color: #ff9800;">Watch Out For:</strong>
                    <ul style="margin-top: 8px;">
                        {% for gap in competitive_gaps[:2] %}
                        <li>{{ gap }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>

        <!-- Key Insights -->
        <div class="section">
            <h2 class="section-title">Key Insights</h2>
            <div class="insight-list">
                {% for insight in insights[:5] %}
                <div class="insight-item">
                    <div class="priority-badge {{ insight.priority }}">{{ loop.index }}</div>
                    <div class="insight-title">{{ insight.title }}</div>
                    <div class="insight-text">{{ insight.description }}</div>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Recommendations -->
        <div class="section">
            <h2 class="section-title">Recommended Actions</h2>
            <div class="recommendation-list">
                {% for rec in recommendations[:5] %}
                <div class="recommendation-item">
                    <div class="priority-badge {{ rec.priority }}">{{ loop.index }}</div>
                    <div class="recommendation-title">{{ rec.title }}</div>
                    <div class="recommendation-text">{{ rec.description }}</div>
                </div>
                {% endfor %}
            </div>

            {% if quick_wins %}
            <div class="quick-wins">
                <h3>⚡ Quick Wins - Implement This Week</h3>
                <ul>
                    {% for win in quick_wins[:3] %}
                    <li>{{ win }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>

        <!-- Footer -->
        <div class="footer">
            <div class="footer-logo">LocalPulse</div>
            <div class="footer-text">AI-Powered Restaurant Intelligence</div>
            <div class="footer-links">
                Generated on {{ generated_at }} | Questions? Reply to this email
            </div>
        </div>
    </div>
</body>
</html>
"""


# =============================================================================
# Node Functions
# =============================================================================


def _get_llm() -> ChatAnthropic:
    """Get configured Claude Haiku instance."""
    settings = get_settings()
    api_key = settings.anthropic_api_key
    if api_key:
        api_key = api_key.get_secret_value()

    return ChatAnthropic(
        model="claude-3-haiku-20240307",
        api_key=api_key,
        temperature=0.5,
        max_tokens=1024,
    )


async def prepare_report_data(state: ReportState) -> dict:
    """Gather analysis results into report structure.

    Args:
        state: Current report state with analysis data.

    Returns:
        Partial state update with prepared report data.
    """
    logger.info("report_prepare_data", business_id=state.get("business_id"))

    analysis = state.get("analysis", {})

    # Extract data from analysis
    sentiment_results = analysis.get("sentiment_results", {})
    theme_results = analysis.get("theme_results", [])
    competitor_analysis = analysis.get("competitor_analysis", {})
    insights = analysis.get("insights", [])
    recommendations = analysis.get("recommendations", [])

    # Get theme data
    theme_data = theme_results[0] if theme_results else {}

    # Prepare report data structure
    report_data = {
        "business_name": sentiment_results.get("business_name", "Your Business"),
        "business_rating": sentiment_results.get("business_rating", 0),
        "sentiment_score": sentiment_results.get("overall_score", 0),
        "sentiment_trend": sentiment_results.get("trend", "stable"),
        "review_count": sentiment_results.get("review_count", 0),
        "positive_count": sentiment_results.get("positive_count", 0),
        "negative_count": sentiment_results.get("negative_count", 0),
        "neutral_count": sentiment_results.get("neutral_count", 0),
        "strengths": theme_data.get("top_strengths", []),
        "weaknesses": theme_data.get("top_weaknesses", []),
        "themes": theme_data.get("themes", []),
        "market_position": competitor_analysis.get("market_position", "competitive"),
        "competitor_count": len(competitor_analysis.get("competitors", [])),
        "competitive_advantages": competitor_analysis.get("competitive_advantages", []),
        "competitive_gaps": competitor_analysis.get("competitive_gaps", []),
        "insights": insights,
        "recommendations": recommendations,
        "quick_wins": sentiment_results.get("quick_wins", []),
        "detailed_insights": sentiment_results.get("detailed_insights", []),
        "detailed_recommendations": sentiment_results.get("detailed_recommendations", []),
    }

    logger.info(
        "report_data_prepared",
        business_name=report_data["business_name"],
        review_count=report_data["review_count"],
    )

    return {
        "report_data": report_data,
        "status": ReportStatus.GENERATING.value,
    }


async def generate_executive_summary(state: ReportState) -> dict:
    """Generate executive summary using Claude.

    Args:
        state: Current state with report data.

    Returns:
        Partial state update with executive summary.
    """
    report_data = state.get("report_data", {})
    business_name = report_data.get("business_name", "Unknown")

    logger.info("report_generate_summary", business_name=business_name)

    try:
        # Get key data points
        sentiment_score = report_data.get("sentiment_score", 0)
        sentiment_trend = report_data.get("sentiment_trend", "stable")
        review_count = report_data.get("review_count", 0)
        market_position = report_data.get("market_position", "competitive")
        strengths = report_data.get("strengths", [])
        weaknesses = report_data.get("weaknesses", [])
        insights = report_data.get("insights", [])
        recommendations = report_data.get("recommendations", [])

        llm = _get_llm()
        structured_llm = llm.with_structured_output(ExecutiveSummary)

        prompt = EXECUTIVE_SUMMARY_PROMPT.format(
            business_name=business_name,
            sentiment_score=round(sentiment_score, 2),
            sentiment_trend=sentiment_trend,
            review_count=review_count,
            market_position=market_position,
            strengths=", ".join(strengths[:3]) if strengths else "Not identified",
            weaknesses=", ".join(weaknesses[:3]) if weaknesses else "Not identified",
            top_insight=insights[0] if insights else "No insights available",
            top_recommendation=recommendations[0] if recommendations else "No recommendations available",
        )

        result: ExecutiveSummary = await structured_llm.ainvoke(prompt)

        logger.info("report_summary_generated")

        return {
            "report_data": {
                **report_data,
                "executive_summary": result.summary,
                "headline": result.headline,
                "key_metric": result.key_metric,
            }
        }

    except Exception as e:
        logger.error("report_summary_failed", error=str(e))
        # Fallback summary
        return {
            "report_data": {
                **report_data,
                "executive_summary": f"Analysis of {report_data.get('review_count', 0)} customer reviews reveals key insights for {business_name}.",
                "headline": f"{business_name} Performance Report",
                "key_metric": f"{round(report_data.get('sentiment_score', 0) * 100)}% Positive",
            },
            "errors": [f"Summary generation failed: {str(e)}"],
        }


async def create_charts_data(state: ReportState) -> dict:
    """Prepare data for visualizations.

    Args:
        state: Current state with report data.

    Returns:
        Partial state update with chart data.
    """
    report_data = state.get("report_data", {})

    logger.info("report_create_charts")

    # Calculate sentiment percentages
    positive = report_data.get("positive_count", 0)
    negative = report_data.get("negative_count", 0)
    neutral = report_data.get("neutral_count", 0)
    total = positive + negative + neutral or 1

    sentiment_breakdown = {
        "positive": (positive / total) * 100,
        "neutral": (neutral / total) * 100,
        "negative": (negative / total) * 100,
    }

    # Prepare theme scores
    themes = report_data.get("themes", [])
    theme_scores = [
        {
            "name": theme.get("name", "Unknown"),
            "score": theme.get("average_sentiment", 0),
            "count": theme.get("mention_count", 0),
            "is_strength": theme.get("is_strength", True),
        }
        for theme in themes[:6]
    ]

    # Rating comparison (client vs average competitor)
    business_rating = report_data.get("business_rating", 0)
    rating_comparison = [
        {"name": report_data.get("business_name", "You"), "rating": business_rating},
        {"name": "Market Average", "rating": 4.2},  # Placeholder
    ]

    chart_data = {
        "sentiment_breakdown": sentiment_breakdown,
        "theme_scores": theme_scores,
        "rating_comparison": rating_comparison,
    }

    logger.info(
        "report_charts_created",
        positive_pct=round(sentiment_breakdown["positive"], 1),
    )

    return {
        "report_data": {
            **report_data,
            "chart_data": chart_data,
            "positive_pct": sentiment_breakdown["positive"],
            "neutral_pct": sentiment_breakdown["neutral"],
            "negative_pct": sentiment_breakdown["negative"],
        }
    }


async def render_html_report(state: ReportState) -> dict:
    """Render the HTML email report.

    Args:
        state: Current state with all report data.

    Returns:
        Partial state update with HTML report.
    """
    report_data = state.get("report_data", {})
    business_name = report_data.get("business_name", "Unknown")

    logger.info("report_render_html", business_name=business_name)

    try:
        # Parse insights and recommendations for template
        insights = report_data.get("insights", [])
        detailed_insights = report_data.get("detailed_insights", [])
        recommendations = report_data.get("recommendations", [])
        detailed_recommendations = report_data.get("detailed_recommendations", [])

        # Convert string insights to dict format for template
        insights_for_template = []
        for i, insight in enumerate(insights[:5]):
            if detailed_insights and i < len(detailed_insights):
                detail = detailed_insights[i]
                insights_for_template.append({
                    "title": detail.get("title", f"Insight {i+1}"),
                    "description": detail.get("description", insight),
                    "priority": detail.get("impact", "medium"),
                })
            else:
                # Parse from string format "[PRIORITY] Title: Description"
                parts = insight.split(": ", 1)
                title = parts[0].replace("[HIGH]", "").replace("[MEDIUM]", "").replace("[LOW]", "").strip()
                description = parts[1] if len(parts) > 1 else insight
                priority = "high" if "[HIGH]" in insight else ("low" if "[LOW]" in insight else "medium")
                insights_for_template.append({
                    "title": title,
                    "description": description,
                    "priority": priority,
                })

        # Convert recommendations similarly
        recommendations_for_template = []
        for i, rec in enumerate(recommendations[:5]):
            if detailed_recommendations and i < len(detailed_recommendations):
                detail = detailed_recommendations[i]
                recommendations_for_template.append({
                    "title": detail.get("title", f"Recommendation {i+1}"),
                    "description": detail.get("description", rec),
                    "priority": detail.get("priority", "medium"),
                })
            else:
                parts = rec.split(": ", 1)
                title = parts[0].replace("[HIGH]", "").replace("[MEDIUM]", "").replace("[LOW]", "").strip()
                description = parts[1] if len(parts) > 1 else rec
                priority = "high" if "[HIGH]" in rec else ("low" if "[LOW]" in rec else "medium")
                recommendations_for_template.append({
                    "title": title,
                    "description": description,
                    "priority": priority,
                })

        # Prepare template variables
        template_vars = {
            "business_name": business_name,
            "report_period": datetime.now(timezone.utc).strftime("%B %Y"),
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            "headline": report_data.get("headline", f"{business_name} Performance Report"),
            "executive_summary": report_data.get("executive_summary", ""),
            "key_metric": report_data.get("key_metric", "N/A"),
            "rating": report_data.get("business_rating", 0),
            "sentiment_score": report_data.get("sentiment_score", 0),
            "trend": report_data.get("sentiment_trend", "stable"),
            "review_count": report_data.get("review_count", 0),
            "positive_pct": report_data.get("positive_pct", 0),
            "neutral_pct": report_data.get("neutral_pct", 0),
            "negative_pct": report_data.get("negative_pct", 0),
            "strengths": report_data.get("strengths", [])[:3],
            "weaknesses": report_data.get("weaknesses", [])[:3],
            "market_position": report_data.get("market_position", "competitive"),
            "competitor_count": report_data.get("competitor_count", 0),
            "competitive_advantages": report_data.get("competitive_advantages", [])[:3],
            "competitive_gaps": report_data.get("competitive_gaps", [])[:2],
            "insights": insights_for_template,
            "recommendations": recommendations_for_template,
            "quick_wins": report_data.get("quick_wins", [])[:3],
        }

        # Render template
        template = Template(HTML_REPORT_TEMPLATE)
        html = template.render(**template_vars)

        logger.info("report_html_rendered", html_length=len(html))

        return {
            "report_html": html,
            "status": ReportStatus.SENDING.value,
        }

    except Exception as e:
        logger.error("report_render_failed", error=str(e))
        return {
            "errors": [f"HTML render failed: {str(e)}"],
            "status": ReportStatus.FAILED.value,
        }


async def send_email(state: ReportState) -> dict:
    """Send the report via SendGrid.

    Args:
        state: Current state with HTML report.

    Returns:
        Partial state update with email status.
    """
    html = state.get("report_html", "")
    report_data = state.get("report_data", {})
    business_name = report_data.get("business_name", "Unknown")

    logger.info("report_send_email", business_name=business_name)

    # For now, we'll skip actual sending and just mark as complete
    # In production, this would use SendGrid API

    try:
        settings = get_settings()
        sendgrid_key = settings.sendgrid_api_key.get_secret_value() if settings.sendgrid_api_key else None

        if not sendgrid_key:
            logger.warning("report_email_skipped", reason="No SendGrid API key")
            return {
                "email_sent": False,
                "status": ReportStatus.COMPLETED.value,
                "errors": ["Email skipped: SendGrid API key not configured"],
            }

        # Placeholder for SendGrid integration
        # In production:
        # import sendgrid
        # from sendgrid.helpers.mail import Mail, Email, To, Content
        # sg = sendgrid.SendGridAPIClient(api_key=sendgrid_key)
        # message = Mail(
        #     from_email=Email("reports@localpulse.ai"),
        #     to_emails=To("owner@restaurant.com"),
        #     subject=f"Your Weekly Intelligence Report - {business_name}",
        #     html_content=Content("text/html", html)
        # )
        # response = sg.send(message)

        logger.info("report_email_sent")

        return {
            "email_sent": True,
            "status": ReportStatus.COMPLETED.value,
        }

    except Exception as e:
        logger.error("report_email_failed", error=str(e))
        return {
            "email_sent": False,
            "errors": [f"Email send failed: {str(e)}"],
            "status": ReportStatus.COMPLETED.value,
        }


# =============================================================================
# Graph Builder
# =============================================================================


def create_report_graph() -> StateGraph:
    """Create the report generation workflow graph.

    The graph executes the following flow:
    1. prepare_report_data - Gather analysis results
    2. generate_executive_summary - Claude writes summary
    3. create_charts_data - Prepare visualization data
    4. render_html_report - Create HTML email
    5. send_email - Send via SendGrid

    Returns:
        StateGraph for report workflow.
    """
    workflow = StateGraph(ReportState)

    # Add nodes
    workflow.add_node("prepare_report_data", prepare_report_data)
    workflow.add_node("generate_executive_summary", generate_executive_summary)
    workflow.add_node("create_charts_data", create_charts_data)
    workflow.add_node("render_html_report", render_html_report)
    workflow.add_node("send_email", send_email)

    # Set entry point
    workflow.set_entry_point("prepare_report_data")

    # Add sequential edges
    workflow.add_edge("prepare_report_data", "generate_executive_summary")
    workflow.add_edge("generate_executive_summary", "create_charts_data")
    workflow.add_edge("create_charts_data", "render_html_report")
    workflow.add_edge("render_html_report", "send_email")
    workflow.add_edge("send_email", END)

    return workflow


def compile_report_graph():
    """Create and compile the report graph.

    Returns:
        Compiled graph ready for invocation.
    """
    graph = create_report_graph()
    return graph.compile()


# =============================================================================
# Convenience Function
# =============================================================================


async def run_report(
    business_id: str,
    analysis: dict[str, Any],
) -> ReportState:
    """Run the report workflow.

    Args:
        business_id: Business ID.
        analysis: Analysis results dict.

    Returns:
        Final ReportState with generated report.
    """
    initial_state = create_report_state(
        business_id=business_id,
        analysis=analysis,
    )

    graph = compile_report_graph()
    final_state = await graph.ainvoke(initial_state)

    return final_state


# =============================================================================
# Test Function
# =============================================================================


def _safe_print(text: str) -> None:
    """Print text safely, handling Unicode issues on Windows."""
    safe_text = text.encode("ascii", errors="replace").decode("ascii")
    print(safe_text)


async def test_report_workflow():
    """Test the report workflow using analysis results.

    Generates the full report and saves HTML to file.
    """
    _safe_print("=" * 70)
    _safe_print("Report Generation Workflow Test")
    _safe_print("=" * 70)

    # Create sample analysis data (mimicking analysis workflow output)
    analysis_data = {
        "sentiment_results": {
            "business_name": "Circolo Popolare Manchester",
            "business_rating": 4.9,
            "overall_score": 0.84,
            "trend": "improving",
            "review_count": 5,
            "positive_count": 4,
            "negative_count": 0,
            "neutral_count": 1,
            "summary": "The sentiment analysis indicates overwhelmingly positive customer feedback.",
            "executive_summary": "Circolo Popolare Manchester excels in customer satisfaction with a strong 84% positive sentiment score.",
            "quick_wins": [
                "Reinforce service training to maintain exceptional standards",
                "Evaluate pricing strategy to ensure strong value perception",
            ],
            "detailed_insights": [
                {"title": "Exceptional Service", "description": "Customers consistently praise the attentive and friendly staff", "impact": "high"},
                {"title": "Food Quality Leader", "description": "Fresh ingredients and authentic Italian flavors drive positive reviews", "impact": "high"},
                {"title": "Ambiance Excellence", "description": "The restaurant atmosphere creates memorable dining experiences", "impact": "medium"},
                {"title": "Value Perception", "description": "Some customers note prices are premium but justified by quality", "impact": "medium"},
                {"title": "Growth Opportunity", "description": "Expanding menu options could attract new customer segments", "impact": "low"},
            ],
            "detailed_recommendations": [
                {"title": "Staff Recognition Program", "description": "Implement a program to reward exceptional service", "priority": "high"},
                {"title": "Seasonal Menu Items", "description": "Introduce rotating seasonal specials to maintain interest", "priority": "medium"},
                {"title": "Loyalty Program", "description": "Create a loyalty program to increase repeat visits", "priority": "medium"},
                {"title": "Social Media Engagement", "description": "Increase social media presence to attract younger demographics", "priority": "low"},
                {"title": "Private Events", "description": "Promote private dining options for corporate events", "priority": "low"},
            ],
        },
        "theme_results": [{
            "top_strengths": ["Food Quality", "Ambiance", "Service"],
            "top_weaknesses": ["Service Inconsistency", "Automatic Service Charge"],
            "themes": [
                {"name": "Food Quality", "average_sentiment": 0.9, "mention_count": 5, "is_strength": True},
                {"name": "Service", "average_sentiment": 0.85, "mention_count": 4, "is_strength": True},
                {"name": "Ambiance", "average_sentiment": 0.8, "mention_count": 3, "is_strength": True},
                {"name": "Value", "average_sentiment": 0.5, "mention_count": 2, "is_strength": False},
            ],
            "summary": "Customers highlight exceptional food quality, service, and ambiance.",
        }],
        "competitor_analysis": {
            "competitors": [{"name": f"Competitor {i}"} for i in range(1, 20)],
            "market_position": "leader",
            "competitive_advantages": [
                "Higher overall customer rating (4.9 vs market average)",
                "Consistent positive feedback on food and service quality",
                "Strong brand reputation in the local market",
            ],
            "competitive_gaps": [
                "Pricing perceived as premium by some customers",
            ],
            "summary": "Circolo Popolare Manchester leads the competitive set with exceptional ratings.",
        },
        "insights": [
            "[HIGH] Maintain Exceptional Service: Customer service is a key differentiator",
            "[HIGH] Strengthen Brand: Leverage positive reputation for marketing",
            "[MEDIUM] Menu Innovation: Introduce seasonal items to maintain interest",
            "[MEDIUM] Value Communication: Better communicate the value proposition",
            "[LOW] Expand Private Dining: Opportunity in corporate events market",
        ],
        "recommendations": [
            "[HIGH] Staff Training Program: Implement ongoing service excellence training",
            "[HIGH] Social Media Strategy: Increase online presence and engagement",
            "[MEDIUM] Loyalty Program: Create rewards for repeat customers",
            "[MEDIUM] Seasonal Menu: Rotate specials to drive repeat visits",
            "[LOW] Private Events: Develop corporate dining packages",
        ],
    }

    business_id = "Circolo Popolare Manchester"

    _safe_print(f"\nGenerating report for: {business_id}")
    _safe_print("-" * 70)

    # Create initial state
    initial_state = create_report_state(
        business_id=business_id,
        analysis=analysis_data,
    )

    _safe_print(f"\nInitial State:")
    _safe_print(f"  Business ID: {business_id}")
    _safe_print(f"  Status: {initial_state.get('status')}")

    # Compile the graph
    graph = compile_report_graph()

    # Run with streaming
    _safe_print("\n" + "=" * 70)
    _safe_print("Workflow Execution:")
    _safe_print("=" * 70)

    step_count = 0
    accumulated_state = dict(initial_state)

    async for event in graph.astream(initial_state):
        step_count += 1
        for node_name, node_state in event.items():
            # Merge updates
            for key, value in node_state.items():
                if key == "errors" and isinstance(value, list):
                    existing = accumulated_state.get(key, [])
                    accumulated_state[key] = existing + value
                else:
                    accumulated_state[key] = value

            _safe_print(f"\n[Step {step_count}] {node_name}")
            _safe_print("-" * 40)

            if node_name == "prepare_report_data":
                report_data = accumulated_state.get("report_data", {})
                _safe_print(f"  Business: {report_data.get('business_name')}")
                _safe_print(f"  Reviews: {report_data.get('review_count')}")
                _safe_print(f"  Sentiment: {report_data.get('sentiment_score')}")

            elif node_name == "generate_executive_summary":
                report_data = accumulated_state.get("report_data", {})
                _safe_print(f"  Headline: {report_data.get('headline', 'N/A')[:50]}...")
                _safe_print(f"  Key Metric: {report_data.get('key_metric', 'N/A')}")

            elif node_name == "create_charts_data":
                report_data = accumulated_state.get("report_data", {})
                _safe_print(f"  Positive: {report_data.get('positive_pct', 0):.1f}%")
                _safe_print(f"  Neutral: {report_data.get('neutral_pct', 0):.1f}%")
                _safe_print(f"  Negative: {report_data.get('negative_pct', 0):.1f}%")

            elif node_name == "render_html_report":
                html = accumulated_state.get("report_html", "")
                _safe_print(f"  HTML Length: {len(html)} characters")

            elif node_name == "send_email":
                _safe_print(f"  Email Sent: {accumulated_state.get('email_sent', False)}")
                _safe_print(f"  Final Status: {accumulated_state.get('status')}")

    # Save HTML to file
    html = accumulated_state.get("report_html", "")
    if html:
        output_path = Path("report_preview.html")
        output_path.write_text(html, encoding="utf-8")
        _safe_print(f"\n[OK] Report saved to: {output_path.absolute()}")

    # Print summary
    _safe_print("\n" + "=" * 70)
    _safe_print("Report Generation Summary:")
    _safe_print("=" * 70)

    _safe_print(f"\n  Status: {accumulated_state.get('status')}")
    _safe_print(f"  HTML Generated: {len(accumulated_state.get('report_html', ''))} chars")
    _safe_print(f"  Email Sent: {accumulated_state.get('email_sent', False)}")

    if accumulated_state.get("errors"):
        _safe_print(f"\n  Errors: {accumulated_state.get('errors')}")

    _safe_print("\n" + "=" * 70)
    _safe_print("Test completed! Open report_preview.html to view the report.")
    _safe_print("=" * 70)

    return accumulated_state


if __name__ == "__main__":
    asyncio.run(test_report_workflow())
