"""SendGrid email service for LocalPulse.

This module provides email delivery functionality using SendGrid API.
It includes methods for sending:
- Weekly/monthly intelligence reports
- Welcome emails for new clients
- System alerts and notifications

Features:
- Automatic retry on failure
- Comprehensive error logging
- HTML and plain text support
- Professional email templates
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from typing import Optional

import structlog
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (
    Mail,
    Email,
    To,
    Content,
    Subject,
    ReplyTo,
    Attachment,
    FileContent,
    FileName,
    FileType,
    Disposition,
)

from src.config.settings import get_settings

logger = structlog.get_logger(__name__)


# =============================================================================
# Email Templates
# =============================================================================


REPORT_EMAIL_WRAPPER = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ business_name }} - Intelligence Report</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
    <!-- Email Preheader (hidden text for email preview) -->
    <div style="display: none; max-height: 0; overflow: hidden;">
        Your {{ report_period }} intelligence report for {{ business_name }} is ready. See key insights and recommendations inside.
    </div>

    <!-- Main Content -->
    {{ report_html }}

    <!-- Email Footer -->
    <table role="presentation" style="width: 100%; max-width: 680px; margin: 0 auto; background-color: #f5f5f5;">
        <tr>
            <td style="padding: 20px 30px; text-align: center;">
                <p style="margin: 0; font-size: 12px; color: #666;">
                    This report was generated by LocalPulse AI on {{ generated_at }}.
                </p>
                <p style="margin: 10px 0 0 0; font-size: 12px; color: #666;">
                    Questions? Reply to this email or contact us at support@localpulse.io
                </p>
                <p style="margin: 15px 0 0 0; font-size: 11px; color: #999;">
                    &copy; {{ year }} LocalPulse. All rights reserved.
                </p>
            </td>
        </tr>
    </table>
</body>
</html>
"""


WELCOME_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to LocalPulse</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
    <!-- Email Preheader -->
    <div style="display: none; max-height: 0; overflow: hidden;">
        Welcome to LocalPulse! Your AI-powered restaurant intelligence platform is ready.
    </div>

    <table role="presentation" style="width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff;">
        <!-- Header -->
        <tr>
            <td style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); padding: 40px 30px; text-align: center;">
                <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700;">LocalPulse</h1>
                <p style="margin: 10px 0 0 0; color: rgba(255,255,255,0.85); font-size: 14px;">AI-Powered Restaurant Intelligence</p>
            </td>
        </tr>

        <!-- Welcome Message -->
        <tr>
            <td style="padding: 40px 30px;">
                <h2 style="margin: 0 0 20px 0; color: #1a1a2e; font-size: 24px;">Welcome, {{ business_name }}!</h2>
                <p style="margin: 0 0 20px 0; color: #333; font-size: 16px; line-height: 1.6;">
                    Thank you for joining LocalPulse. We're excited to help you understand your customers better and grow your business.
                </p>
                <p style="margin: 0 0 20px 0; color: #333; font-size: 16px; line-height: 1.6;">
                    Your first intelligence report is being prepared and will be delivered to this email address {{ frequency }}.
                </p>
            </td>
        </tr>

        <!-- What to Expect -->
        <tr>
            <td style="padding: 0 30px 30px 30px;">
                <div style="background: #f8f9fa; border-radius: 12px; padding: 25px;">
                    <h3 style="margin: 0 0 15px 0; color: #1a1a2e; font-size: 18px;">What to Expect</h3>
                    <table role="presentation" style="width: 100%;">
                        <tr>
                            <td style="padding: 10px 0; vertical-align: top; width: 30px;">
                                <span style="color: #667eea; font-size: 18px;">&#x2713;</span>
                            </td>
                            <td style="padding: 10px 0; color: #555; font-size: 14px;">
                                <strong>Sentiment Analysis</strong> - Understand how customers feel about your business
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; vertical-align: top; width: 30px;">
                                <span style="color: #667eea; font-size: 18px;">&#x2713;</span>
                            </td>
                            <td style="padding: 10px 0; color: #555; font-size: 14px;">
                                <strong>Competitive Intelligence</strong> - See how you compare to local competitors
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; vertical-align: top; width: 30px;">
                                <span style="color: #667eea; font-size: 18px;">&#x2713;</span>
                            </td>
                            <td style="padding: 10px 0; color: #555; font-size: 14px;">
                                <strong>AI Insights</strong> - Get actionable recommendations to improve
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; vertical-align: top; width: 30px;">
                                <span style="color: #667eea; font-size: 18px;">&#x2713;</span>
                            </td>
                            <td style="padding: 10px 0; color: #555; font-size: 14px;">
                                <strong>Trend Tracking</strong> - Monitor your progress over time
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>

        <!-- Next Steps -->
        <tr>
            <td style="padding: 0 30px 40px 30px;">
                <h3 style="margin: 0 0 15px 0; color: #1a1a2e; font-size: 18px;">Your Schedule</h3>
                <p style="margin: 0; color: #555; font-size: 14px; line-height: 1.6;">
                    Your reports will be delivered <strong>{{ frequency }}</strong> to this email address.
                    Your first report will arrive {{ first_report_info }}.
                </p>
            </td>
        </tr>

        <!-- CTA Button -->
        <tr>
            <td style="padding: 0 30px 40px 30px; text-align: center;">
                <p style="margin: 0 0 15px 0; color: #666; font-size: 14px;">
                    Have questions? We're here to help.
                </p>
                <a href="mailto:support@localpulse.io" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; text-decoration: none; padding: 14px 30px; border-radius: 8px; font-size: 14px; font-weight: 600;">
                    Contact Support
                </a>
            </td>
        </tr>

        <!-- Footer -->
        <tr>
            <td style="background: #1a1a2e; padding: 25px 30px; text-align: center;">
                <p style="margin: 0; color: rgba(255,255,255,0.7); font-size: 12px;">
                    &copy; {{ year }} LocalPulse. All rights reserved.
                </p>
                <p style="margin: 10px 0 0 0; color: rgba(255,255,255,0.5); font-size: 11px;">
                    You're receiving this email because you signed up for LocalPulse.
                </p>
            </td>
        </tr>
    </table>
</body>
</html>
"""


ALERT_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ subject }}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
    <table role="presentation" style="width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff;">
        <!-- Header -->
        <tr>
            <td style="background: linear-gradient(135deg, {{ header_color_start }} 0%, {{ header_color_end }} 100%); padding: 30px; text-align: center;">
                <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 700;">
                    {{ alert_icon }} {{ subject }}
                </h1>
            </td>
        </tr>

        <!-- Alert Content -->
        <tr>
            <td style="padding: 40px 30px;">
                <div style="background: {{ alert_bg_color }}; border-left: 4px solid {{ alert_border_color }}; padding: 20px; border-radius: 0 8px 8px 0; margin-bottom: 25px;">
                    <p style="margin: 0; color: #333; font-size: 16px; line-height: 1.6;">
                        {{ message }}
                    </p>
                </div>

                {% if details %}
                <div style="margin-top: 20px;">
                    <h3 style="margin: 0 0 15px 0; color: #1a1a2e; font-size: 16px;">Details</h3>
                    <p style="margin: 0; color: #555; font-size: 14px; line-height: 1.6; white-space: pre-wrap;">{{ details }}</p>
                </div>
                {% endif %}

                <p style="margin: 25px 0 0 0; color: #666; font-size: 13px;">
                    <strong>Time:</strong> {{ timestamp }}
                </p>
            </td>
        </tr>

        <!-- Action Button (optional) -->
        {% if action_url %}
        <tr>
            <td style="padding: 0 30px 40px 30px; text-align: center;">
                <a href="{{ action_url }}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; text-decoration: none; padding: 14px 30px; border-radius: 8px; font-size: 14px; font-weight: 600;">
                    {{ action_text }}
                </a>
            </td>
        </tr>
        {% endif %}

        <!-- Footer -->
        <tr>
            <td style="background: #f8f9fa; padding: 20px 30px; text-align: center; border-top: 1px solid #eee;">
                <p style="margin: 0; color: #666; font-size: 12px;">
                    This is an automated alert from LocalPulse.
                </p>
                <p style="margin: 10px 0 0 0; color: #999; font-size: 11px;">
                    &copy; {{ year }} LocalPulse. All rights reserved.
                </p>
            </td>
        </tr>
    </table>
</body>
</html>
"""


# Plain text fallbacks
REPORT_EMAIL_PLAIN = """
{{ business_name }} - Intelligence Report
{{ report_period }}

{{ executive_summary }}

Key Highlights:
- Sentiment Score: {{ sentiment_score }}%
- Reviews Analyzed: {{ review_count }}
- Market Position: {{ market_position }}

View the full HTML report in your email client for the complete analysis with charts and visualizations.

---
Generated by LocalPulse on {{ generated_at }}
Questions? Reply to this email or contact support@localpulse.io
"""


WELCOME_EMAIL_PLAIN = """
Welcome to LocalPulse, {{ business_name }}!

Thank you for joining LocalPulse. We're excited to help you understand your customers better and grow your business.

What to Expect:
- Sentiment Analysis: Understand how customers feel about your business
- Competitive Intelligence: See how you compare to local competitors
- AI Insights: Get actionable recommendations to improve
- Trend Tracking: Monitor your progress over time

Your Schedule:
Your reports will be delivered {{ frequency }} to this email address.
Your first report will arrive {{ first_report_info }}.

Have questions? Contact us at support@localpulse.io

---
LocalPulse - AI-Powered Restaurant Intelligence
"""


ALERT_EMAIL_PLAIN = """
{{ subject }}

{{ message }}

{% if details %}
Details:
{{ details }}
{% endif %}

Time: {{ timestamp }}

---
This is an automated alert from LocalPulse.
"""


# =============================================================================
# Email Service Class
# =============================================================================


class EmailService:
    """SendGrid-based email service for LocalPulse.

    Provides methods for sending various types of emails with automatic
    retry logic and comprehensive error handling.

    Example:
        service = EmailService()
        success = await service.send_report(
            to_email="owner@restaurant.com",
            business_name="My Restaurant",
            report_html="<html>...</html>",
            report_date="January 2024",
        )
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        from_email: Optional[str] = None,
        from_name: Optional[str] = None,
        reply_to: Optional[str] = None,
    ):
        """Initialize the email service.

        Args:
            api_key: SendGrid API key. Defaults to settings.
            from_email: Sender email address. Defaults to settings.
            from_name: Sender display name. Defaults to settings.
            reply_to: Reply-to email address. Defaults to settings.
        """
        settings = get_settings()

        self._api_key = api_key or (
            settings.sendgrid_api_key.get_secret_value()
            if settings.sendgrid_api_key else None
        )
        self._from_email = from_email or getattr(settings, 'from_email', 'reports@localpulse.io')
        self._from_name = from_name or getattr(settings, 'from_name', 'LocalPulse')
        self._reply_to = reply_to or getattr(settings, 'reply_to_email', 'support@localpulse.io')

        self._client: Optional[SendGridAPIClient] = None

        if self._api_key:
            self._client = SendGridAPIClient(api_key=self._api_key)
            logger.info("email_service_initialized", from_email=self._from_email)
        else:
            logger.warning("email_service_no_api_key", message="SendGrid API key not configured")

    @property
    def is_configured(self) -> bool:
        """Check if the email service is properly configured."""
        return self._client is not None

    def _render_template(self, template: str, **kwargs) -> str:
        """Render an email template with Jinja2.

        Args:
            template: Template string with Jinja2 syntax.
            **kwargs: Template variables.

        Returns:
            Rendered template string.
        """
        from jinja2 import Template

        # Add common variables
        kwargs.setdefault("year", datetime.now().year)

        jinja_template = Template(template)
        return jinja_template.render(**kwargs)

    async def _send_email(
        self,
        to_email: str,
        subject: str,
        html_content: str,
        plain_content: Optional[str] = None,
        retry: bool = True,
    ) -> bool:
        """Send an email via SendGrid with retry logic.

        Args:
            to_email: Recipient email address.
            subject: Email subject line.
            html_content: HTML email body.
            plain_content: Plain text fallback.
            retry: Whether to retry on failure.

        Returns:
            True if sent successfully, False otherwise.
        """
        if not self._client:
            logger.error("email_send_failed", reason="SendGrid client not configured")
            return False

        message = Mail(
            from_email=Email(self._from_email, self._from_name),
            to_emails=To(to_email),
            subject=Subject(subject),
        )

        # Add HTML content
        message.add_content(Content("text/html", html_content))

        # Add plain text fallback
        if plain_content:
            message.add_content(Content("text/plain", plain_content))

        # Add reply-to
        message.reply_to = ReplyTo(self._reply_to)

        # Attempt to send
        for attempt in range(2 if retry else 1):
            try:
                response = self._client.send(message)

                if response.status_code in (200, 201, 202):
                    logger.info(
                        "email_sent",
                        to=to_email,
                        subject=subject[:50],
                        status_code=response.status_code,
                    )
                    return True
                else:
                    logger.warning(
                        "email_send_unexpected_status",
                        to=to_email,
                        status_code=response.status_code,
                        body=response.body,
                    )

            except Exception as e:
                logger.error(
                    "email_send_error",
                    to=to_email,
                    attempt=attempt + 1,
                    error=str(e),
                )

                if retry and attempt == 0:
                    # Wait before retry
                    await asyncio.sleep(2)
                    continue

                return False

        return False

    async def send_report(
        self,
        to_email: str,
        business_name: str,
        report_html: str,
        report_date: str,
    ) -> bool:
        """Send an intelligence report email.

        Args:
            to_email: Recipient email address.
            business_name: Name of the business.
            report_html: Generated HTML report content.
            report_date: Report period (e.g., "January 2024").

        Returns:
            True if sent successfully, False otherwise.
        """
        logger.info(
            "sending_report_email",
            to=to_email,
            business_name=business_name,
        )

        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Wrap report HTML in email template
        html_content = self._render_template(
            REPORT_EMAIL_WRAPPER,
            business_name=business_name,
            report_period=report_date,
            report_html=report_html,
            generated_at=generated_at,
        )

        # Create plain text fallback
        plain_content = self._render_template(
            REPORT_EMAIL_PLAIN,
            business_name=business_name,
            report_period=report_date,
            executive_summary="Your intelligence report is ready. Please view this email in an HTML-capable email client for the full report.",
            sentiment_score="N/A",
            review_count="N/A",
            market_position="N/A",
            generated_at=generated_at,
        )

        subject = f"Your {report_date} Intelligence Report - {business_name}"

        return await self._send_email(
            to_email=to_email,
            subject=subject,
            html_content=html_content,
            plain_content=plain_content,
        )

    async def send_welcome_email(
        self,
        to_email: str,
        business_name: str,
        frequency: str = "weekly",
        first_report_info: str = "within the next 7 days",
    ) -> bool:
        """Send a welcome email to a new client.

        Args:
            to_email: Recipient email address.
            business_name: Name of the business.
            frequency: Report frequency (daily, weekly, monthly).
            first_report_info: Information about when first report arrives.

        Returns:
            True if sent successfully, False otherwise.
        """
        logger.info(
            "sending_welcome_email",
            to=to_email,
            business_name=business_name,
        )

        # Format frequency for display
        frequency_display = {
            "daily": "every day",
            "weekly": "every week",
            "monthly": "every month",
        }.get(frequency, frequency)

        html_content = self._render_template(
            WELCOME_EMAIL_TEMPLATE,
            business_name=business_name,
            frequency=frequency_display,
            first_report_info=first_report_info,
        )

        plain_content = self._render_template(
            WELCOME_EMAIL_PLAIN,
            business_name=business_name,
            frequency=frequency_display,
            first_report_info=first_report_info,
        )

        subject = f"Welcome to LocalPulse, {business_name}!"

        return await self._send_email(
            to_email=to_email,
            subject=subject,
            html_content=html_content,
            plain_content=plain_content,
        )

    async def send_alert(
        self,
        to_email: str,
        subject: str,
        message: str,
        alert_type: str = "info",
        details: Optional[str] = None,
        action_url: Optional[str] = None,
        action_text: str = "View Details",
    ) -> bool:
        """Send an alert/notification email.

        Args:
            to_email: Recipient email address.
            subject: Alert subject line.
            message: Alert message content.
            alert_type: Type of alert (info, warning, error, success).
            details: Additional details to include.
            action_url: Optional URL for action button.
            action_text: Text for the action button.

        Returns:
            True if sent successfully, False otherwise.
        """
        logger.info(
            "sending_alert_email",
            to=to_email,
            subject=subject,
            alert_type=alert_type,
        )

        # Configure colors based on alert type
        alert_configs = {
            "info": {
                "header_color_start": "#667eea",
                "header_color_end": "#764ba2",
                "alert_bg_color": "#e3f2fd",
                "alert_border_color": "#2196f3",
                "alert_icon": "&#x2139;",  # Info icon
            },
            "warning": {
                "header_color_start": "#ff9800",
                "header_color_end": "#f57c00",
                "alert_bg_color": "#fff3e0",
                "alert_border_color": "#ff9800",
                "alert_icon": "&#x26A0;",  # Warning icon
            },
            "error": {
                "header_color_start": "#f44336",
                "header_color_end": "#d32f2f",
                "alert_bg_color": "#ffebee",
                "alert_border_color": "#f44336",
                "alert_icon": "&#x2717;",  # X icon
            },
            "success": {
                "header_color_start": "#4caf50",
                "header_color_end": "#388e3c",
                "alert_bg_color": "#e8f5e9",
                "alert_border_color": "#4caf50",
                "alert_icon": "&#x2713;",  # Checkmark
            },
        }

        config = alert_configs.get(alert_type, alert_configs["info"])
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        html_content = self._render_template(
            ALERT_EMAIL_TEMPLATE,
            subject=subject,
            message=message,
            details=details,
            timestamp=timestamp,
            action_url=action_url,
            action_text=action_text,
            **config,
        )

        plain_content = self._render_template(
            ALERT_EMAIL_PLAIN,
            subject=subject,
            message=message,
            details=details,
            timestamp=timestamp,
        )

        return await self._send_email(
            to_email=to_email,
            subject=f"[LocalPulse] {subject}",
            html_content=html_content,
            plain_content=plain_content,
        )


# =============================================================================
# Singleton Instance
# =============================================================================

_email_service: Optional[EmailService] = None


def get_email_service() -> EmailService:
    """Get the singleton EmailService instance.

    Returns:
        EmailService instance.
    """
    global _email_service
    if _email_service is None:
        _email_service = EmailService()
    return _email_service


# =============================================================================
# Test Functions
# =============================================================================


async def test_send_report():
    """Test sending a report email."""
    print("=" * 70)
    print("Email Service - Report Email Test")
    print("=" * 70)

    service = EmailService()

    if not service.is_configured:
        print("\nSendGrid API key not configured. Set SENDGRID_API_KEY in .env")
        print("Skipping actual email send.")
        return False

    # Sample report HTML
    sample_html = """
    <div style="padding: 20px; background: #fff;">
        <h1 style="color: #1a1a2e;">Sample Report</h1>
        <p>This is a test report email from LocalPulse.</p>
        <div style="background: #f0f0f0; padding: 15px; border-radius: 8px; margin-top: 15px;">
            <strong>Key Metrics:</strong>
            <ul>
                <li>Sentiment Score: 85%</li>
                <li>Reviews Analyzed: 42</li>
                <li>Market Position: Leader</li>
            </ul>
        </div>
    </div>
    """

    # Get test email from user input or environment
    import os
    test_email = os.environ.get("TEST_EMAIL", "")

    if not test_email:
        print("\nSet TEST_EMAIL environment variable to run the test.")
        print("Example: TEST_EMAIL=your@email.com python -m src.delivery.email_service")
        return False

    print(f"\nSending test report to: {test_email}")

    success = await service.send_report(
        to_email=test_email,
        business_name="Test Restaurant",
        report_html=sample_html,
        report_date="January 2024",
    )

    print(f"\nResult: {'Success!' if success else 'Failed'}")
    return success


async def test_send_welcome():
    """Test sending a welcome email."""
    print("=" * 70)
    print("Email Service - Welcome Email Test")
    print("=" * 70)

    service = EmailService()

    if not service.is_configured:
        print("\nSendGrid API key not configured.")
        return False

    import os
    test_email = os.environ.get("TEST_EMAIL", "")

    if not test_email:
        print("\nSet TEST_EMAIL environment variable to run the test.")
        return False

    print(f"\nSending welcome email to: {test_email}")

    success = await service.send_welcome_email(
        to_email=test_email,
        business_name="Test Restaurant",
        frequency="weekly",
        first_report_info="within the next 7 days",
    )

    print(f"\nResult: {'Success!' if success else 'Failed'}")
    return success


async def test_send_alert():
    """Test sending an alert email."""
    print("=" * 70)
    print("Email Service - Alert Email Test")
    print("=" * 70)

    service = EmailService()

    if not service.is_configured:
        print("\nSendGrid API key not configured.")
        return False

    import os
    test_email = os.environ.get("TEST_EMAIL", "")

    if not test_email:
        print("\nSet TEST_EMAIL environment variable to run the test.")
        return False

    print(f"\nSending alert email to: {test_email}")

    success = await service.send_alert(
        to_email=test_email,
        subject="Test Alert",
        message="This is a test alert from LocalPulse. If you received this, the email service is working correctly.",
        alert_type="info",
        details="Alert Type: Test\nSource: email_service.py\nEnvironment: Development",
    )

    print(f"\nResult: {'Success!' if success else 'Failed'}")
    return success


async def run_all_tests():
    """Run all email tests."""
    print("\n" + "=" * 70)
    print("Running All Email Service Tests")
    print("=" * 70 + "\n")

    await test_send_report()
    print()
    await test_send_welcome()
    print()
    await test_send_alert()

    print("\n" + "=" * 70)
    print("All tests completed!")
    print("=" * 70)


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        test_type = sys.argv[1].lower()
        if test_type == "report":
            asyncio.run(test_send_report())
        elif test_type == "welcome":
            asyncio.run(test_send_welcome())
        elif test_type == "alert":
            asyncio.run(test_send_alert())
        else:
            print(f"Unknown test type: {test_type}")
            print("Usage: python -m src.delivery.email_service [report|welcome|alert]")
    else:
        asyncio.run(run_all_tests())
